package com.acttub.actingapi.feature.auth.adapter.db;
import java.sql.ResultSet; import java.sql.SQLException; import java.time.*; import java.util.*; import com.acttub.actingapi.feature.auth.app.AuthRepository; import com.acttub.actingapi.feature.auth.app.IdentityAlreadyLinkedError; import com.acttub.actingapi.feature.auth.domain.RefreshToken; import com.acttub.actingapi.platform.schema.UserStatus; import com.acttub.actingapi.platform.security.AuthenticatedUser; import com.acttub.actingapi.platform.security.AuthenticatedUsers; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import org.springframework.transaction.support.TransactionTemplate;
/**
 * 사용자를 소유한 쪽이 배관의 포트를 <b>직접</b> 구현한다 — 위임만 하는 어댑터를 끼우지
 * 않는다 (ADR-017, SOMA-397 6단계의 {@code SyncOperationService} 와 같은 형태).
 *
 * <p>동의 여부는 여기 없다. 동의 문서와 그 이력을 소유한 쪽은 {@code consent} 이고, 게이트가
 * 묻는 것({@code PendingConsentGate})도 로그인 응답에 실리는 목록({@code auth/app/
 * PendingConsentDocuments})도 그쪽이 답한다 (SOMA-397 12단계).
 */
@Repository public class PostgresAuthRepository implements AuthRepository, AuthenticatedUsers {
    private final JdbcTemplate jdbc;private final TransactionTemplate tx;public PostgresAuthRepository(JdbcTemplate jdbc,TransactionTemplate tx){this.jdbc=jdbc;this.tx=tx;}
    @Override public AuthenticatedUser find(UUID id){return one("SELECT id,email,status FROM users WHERE id=?",id);}
    @Override public AuthenticatedUser findByEmail(String email){return one("SELECT id,email,status FROM users WHERE lower(email)=lower(?)",email);}
    @Override public AuthenticatedUser findByIdentity(String provider,String uid){return one("SELECT u.id,u.email,u.status FROM users u JOIN user_identities i ON i.user_id=u.id WHERE i.provider=? AND i.provider_uid=?",provider,uid);}
    private AuthenticatedUser one(String sql,Object...args){List<AuthenticatedUser> values=jdbc.query(sql,(rs,n)->new AuthenticatedUser(rs.getObject(1,UUID.class),rs.getString(2),UserStatus.valueOf(rs.getString(3).toUpperCase(Locale.ROOT))),args);return values.isEmpty()?null:values.getFirst();}
    @Override public AuthenticatedUser createUserWithIdentity(String provider,String uid,String email){return tx.execute(s->{UUID id=UUID.randomUUID();jdbc.update("INSERT INTO users(id,email,status) VALUES (?,?,'active')",id,email);jdbc.update("INSERT INTO user_identities(id,user_id,provider,provider_uid) VALUES (?,?,?,?)",UUID.randomUUID(),id,provider,uid);return find(id);});}
    @Override public void linkIdentity(UUID user,String provider,String uid){int inserted=jdbc.update("INSERT INTO user_identities(id,user_id,provider,provider_uid) VALUES (?,?,?,?) ON CONFLICT(provider,provider_uid) DO NOTHING",UUID.randomUUID(),user,provider,uid);if(inserted==0){List<UUID> owners=jdbc.query("SELECT user_id FROM user_identities WHERE provider=? AND provider_uid=?",(rs,n)->rs.getObject(1,UUID.class),provider,uid);if(owners.isEmpty()||!owners.getFirst().equals(user))throw new IdentityAlreadyLinkedError("identity is already linked to another user");}}
    @Override public void issueRefresh(UUID user,String hash,Instant expires,String device,Instant issued){validateHash(hash);jdbc.update("INSERT INTO refresh_tokens(id,user_id,token_hash,device_info,issued_at,expires_at) VALUES (?,?,?,?,?,?)",UUID.randomUUID(),user,hash,device,issued.atOffset(ZoneOffset.UTC),expires.atOffset(ZoneOffset.UTC));}
    @Override public RefreshToken getRefresh(String hash){validateHash(hash);List<RefreshToken> rows=jdbc.query("SELECT id,user_id,replaced_by_id,expires_at,revoked_at,device_info FROM refresh_tokens WHERE token_hash=?",PostgresAuthRepository::refresh,hash);return rows.isEmpty()?null:rows.getFirst();}
    /**
     * 판정과 교체가 한 트랜잭션·한 잠금 안에서 난다. 무엇이 재사용이고 무엇이 만료인지는
     * {@link RefreshToken} 이 정하고, 여기서는 {@code FOR UPDATE} 로 잡은 채 그것을 묻는다.
     */
    @Override public Rotation rotate(String oldHash,String newHash,Instant expires,String device,Instant now){validateHash(oldHash);validateHash(newHash);return tx.execute(s->{List<RefreshToken> rows=jdbc.query("SELECT id,user_id,replaced_by_id,expires_at,revoked_at,device_info FROM refresh_tokens WHERE token_hash=? FOR UPDATE",PostgresAuthRepository::refresh,oldHash);if(rows.isEmpty())return new Rotation(null,false);RefreshToken old=rows.getFirst();if(old.reused()){jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL",now.atOffset(ZoneOffset.UTC),old.userId());return new Rotation(null,true);}if(old.revoked()||old.expiredAt(now)){if(!old.revoked())jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE id=?",now.atOffset(ZoneOffset.UTC),old.id());return new Rotation(null,false);}UUID replacement=UUID.randomUUID();jdbc.update("INSERT INTO refresh_tokens(id,user_id,token_hash,device_info,issued_at,expires_at) VALUES (?,?,?,?,?,?)",replacement,old.userId(),newHash,device!=null?device:old.deviceInfo(),now.atOffset(ZoneOffset.UTC),expires.atOffset(ZoneOffset.UTC));jdbc.update("UPDATE refresh_tokens SET replaced_by_id=?,revoked_at=? WHERE id=?",replacement,now.atOffset(ZoneOffset.UTC),old.id());return new Rotation(replacement,false);});}
    @Override public boolean revoke(String hash,Instant now){validateHash(hash);return jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL",now.atOffset(ZoneOffset.UTC),hash)>0;}
    private static RefreshToken refresh(ResultSet rs,int n)throws SQLException{return new RefreshToken(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getObject(3,UUID.class),rs.getObject(4,java.time.OffsetDateTime.class).toInstant(),rs.getObject(5,java.time.OffsetDateTime.class)==null?null:rs.getObject(5,java.time.OffsetDateTime.class).toInstant(),rs.getString(6));}
    private static void validateHash(String value){if(value==null||!value.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("expected SHA-256 hex");}
}
