/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v2_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_v2_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v2_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/consents/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_v2_consents_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Consent */
        post: operations["record_consent_v2_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/uploads/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Intent */
        post: operations["create_intent_v2_uploads_intents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/uploads/intents/{intent_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Intent */
        post: operations["complete_intent_v2_uploads_intents__intent_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sessions */
        get: operations["list_sessions_v2_practice_sessions_get"];
        put?: never;
        /** Create Session */
        post: operations["create_session_v2_practice_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/practice-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session */
        get: operations["get_session_v2_practice_sessions__session_id__get"];
        put?: never;
        post?: never;
        /** Delete Session */
        delete: operations["delete_session_v2_practice_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/practice-sessions/{session_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reanalyze Session */
        post: operations["reanalyze_session_v2_practice_sessions__session_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/coach/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coach Start */
        post: operations["coach_start_v2_coach_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/coach/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Coach Reply */
        post: operations["coach_reply_v2_coach_reply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report History */
        get: operations["report_history_v2_reports_get"];
        put?: never;
        /** Create Report */
        post: operations["create_report_v2_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActingReport */
        ActingReport: {
            /** Headline */
            headline: string;
            biggest_problem: components["schemas"]["BiggestProblem"];
            /** Evidence */
            evidence: string;
            /** Self Discovery */
            self_discovery: string;
            /** Encouragement */
            encouragement: string;
            /** Next Step */
            next_step: string;
            /** Comparison */
            comparison: string;
        };
        /** AuthUser */
        AuthUser: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "suspended";
        };
        /** BiggestProblem */
        BiggestProblem: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Dimension */
            dimension: string;
            /** Description */
            description: string;
        };
        /** CoachReplyReq */
        CoachReplyReq: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Text */
            text: string;
        };
        /** CoachStartReq */
        CoachStartReq: {
            /**
             * Summary Id
             * Format: uuid
             */
            summary_id: string;
        };
        /** CoachTurnResponse */
        CoachTurnResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Action
             * @enum {string}
             */
            action: "probe_intent" | "dig_cause" | "deflect" | "close";
            /** Utterance */
            utterance: string;
            /** Focus Timestamp */
            focus_timestamp: string;
            /** Done */
            done: boolean;
            /** Reason */
            reason: ("gap_stated" | "exhausted" | "limit" | "user_ended") | null;
        };
        /**
         * ConsentAction
         * @enum {string}
         */
        ConsentAction: "granted" | "declined" | "revoked";
        /** ConsentDocument */
        ConsentDocument: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            type: components["schemas"]["ConsentType"];
            /** Version */
            version: string;
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Required */
            required: boolean;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
        };
        /** ConsentDocumentsResponse */
        ConsentDocumentsResponse: {
            /** Documents */
            documents: components["schemas"]["ConsentDocument"][];
        };
        /** ConsentEventResponse */
        ConsentEventResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            action: components["schemas"]["ConsentAction"];
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /** ConsentRequest */
        ConsentRequest: {
            /** Document Id */
            document_id: string;
            action: components["schemas"]["ConsentAction"];
        };
        /**
         * ConsentType
         * @enum {string}
         */
        ConsentType: "terms" | "privacy" | "ai_analysis";
        /** CreateReportResponse */
        CreateReportResponse: {
            report: components["schemas"]["ActingReport"];
            /** Report Count */
            report_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Services */
            services: string[];
            /** Model */
            model: string;
            /** Keep Alive */
            keep_alive: boolean;
            /** Commit */
            commit: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Provider */
            provider: string;
            /** Id Token */
            id_token: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** PracticeSessionAcceptedResponse */
        PracticeSessionAcceptedResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @constant
             */
            status: "analyzing";
        };
        /** PracticeSessionCreateResponse */
        PracticeSessionCreateResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "analyzing" | "analyzed" | "failed";
            /** Summary Id */
            summary_id?: string | null;
        };
        /** PracticeSessionDetail */
        PracticeSessionDetail: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "analyzing" | "analyzed" | "failed";
            /** Situation */
            situation: string;
            /** Character Context */
            character_context: string;
            /** Subtext */
            subtext: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Playback Url */
            playback_url: string;
            summary?: components["schemas"]["SceneSummary"] | null;
            /** Error Code */
            error_code?: ("gemini_timeout" | "gemini_parse_error" | "unsupported_media" | "max_attempts_exceeded") | null;
        };
        /** PracticeSessionListItem */
        PracticeSessionListItem: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "created" | "analyzing" | "analyzed" | "failed";
            /** Situation */
            situation: string;
            /** Character Context */
            character_context: string;
            /** Subtext */
            subtext: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PracticeSessionListResponse */
        PracticeSessionListResponse: {
            /** Sessions */
            sessions: components["schemas"]["PracticeSessionListItem"][];
        };
        /** PracticeSessionRequest */
        PracticeSessionRequest: {
            /**
             * Upload Intent Id
             * Format: uuid
             */
            upload_intent_id: string;
            /** Situation */
            situation: string;
            /** Character Context */
            character_context: string;
            /** Subtext */
            subtext: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RefreshTokenResponse */
        RefreshTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
            /** Expires In */
            expires_in: number;
        };
        /** ReportHistoryResponse */
        ReportHistoryResponse: {
            /** Count */
            count: number;
            /** Reports */
            reports: components["schemas"]["ReportRecord"][];
        };
        /** ReportRecord */
        ReportRecord: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /**
             * Practice Session Id
             * Format: uuid
             */
            practice_session_id: string;
            report: components["schemas"]["ActingReport"];
        };
        /** ReportReq */
        ReportReq: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
        };
        /** SceneSummary */
        SceneSummary: {
            /**
             * Summary Id
             * Format: uuid
             */
            summary_id: string;
            /** Observation */
            observation?: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary?: string | null;
            /** Intent Alignment */
            intent_alignment?: string | null;
            /** Key Moment */
            key_moment?: string | null;
            /** Key Dimension */
            key_dimension?: string | null;
            /** Anomalies */
            anomalies?: {
                [key: string]: unknown;
            }[] | null;
        } & {
            [key: string]: unknown;
        };
        /** TokenPairResponse */
        TokenPairResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /** Token Type */
            token_type: string;
            /** Expires In */
            expires_in: number;
            user: components["schemas"]["AuthUser"];
            /** Pending Consents */
            pending_consents: components["schemas"]["ConsentDocument"][];
        };
        /** UploadCompleteResponse */
        UploadCompleteResponse: {
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /**
             * Status
             * @constant
             */
            status: "finalized";
        };
        /** UploadIntentRequest */
        UploadIntentRequest: {
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Duration Ms */
            duration_ms?: number | null;
        };
        /** UploadIntentResponse */
        UploadIntentResponse: {
            /**
             * Intent Id
             * Format: uuid
             */
            intent_id: string;
            /** Upload Url */
            upload_url: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_v2_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_v2_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v2_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_v2_consents_documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentDocumentsResponse"];
                };
            };
        };
    };
    record_consent_v2_consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentEventResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intent_v2_uploads_intents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadIntentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadIntentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_intent_v2_uploads_intents__intent_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadCompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_v2_practice_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionListResponse"];
                };
            };
        };
    };
    create_session_v2_practice_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionCreateResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_v2_practice_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_v2_practice_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_session_v2_practice_sessions__session_id__analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionCreateResponse"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionAcceptedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_start_v2_coach_start_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachStartReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    coach_reply_v2_coach_reply_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoachReplyReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoachTurnResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_history_v2_reports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportHistoryResponse"];
                };
            };
        };
    };
    create_report_v2_reports_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateReportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
