import assert from 'node:assert/strict';
import test from 'node:test';
import {createAiPipelineService} from '../src/server/ai-pipeline-service-core.js';
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const ids={session:id(1),user:id(2),summary:id(3),take:id(4),observation:id(5)};
const normalized={schemaVersion:'scene-summary.v1',subtextStatus:'not_provided',observation:{timeline:'t',dialogue:'d',tempo:'t',pitch:'p',movement:'m',expression:'e',emotion:'e',extra:[]},summary:'s',intentAlignment:null,keyMoment:null,keyDimension:null,anomalies:[]};
const base=()=>({sessionId:ids.session,userId:ids.user,pipelineVersion:'ai-pipeline.v1',requiredConsentVersionSnapshot:'v1',aiProcessingConsentVersionSnapshot:'v1',interviewStatus:'active',completionReason:null,substantiveAnswerCount:0,reportEvidenceObservationIds:[],reportEvidenceAnswerTurnIds:[],sceneContext:{genre:'drama',situation:'scene',characterContext:'actor',subtext:null},take:{id:ids.take,storageBucket:'practice-videos',storagePath:'u/s/video.mp4',durationMs:1000,mediaMetadataVersion:'iso-bmff-duration.v1'},summary:{sourceRunId:ids.summary,normalizedSummary:normalized},observations:[{id:ids.observation,candidateId:ids.observation,sourceRunId:ids.summary,confirmationState:'accepted',blockedForQuestioning:false,priority:1,startMs:0,endMs:1,text:'evidence',dimension:'voice',severity:'mid'}],corrections:[],transcript:[],runs:[],optionalNote:null,report:null});
const reportable=s=>s.transcript.filter(t=>t.role==='actor'&&(t.kind==='answer'||t.kind==='unknown')).length;
const harness=({appendFault='none',reloadFailures=0}={})=>{
 const session=base(), claims=new Map(), e={provider:0,append:0,fail:0,failedReads:0,claims:[],failInputs:[],requests:[]};let fault=appendFault==='none'?0:1,remaining=reloadFailures,committed=false;
 const repository={
  async findPipelineSessionForOwner(){if(committed&&remaining>0){remaining--;e.failedReads++;throw new Error('post-commit reload unavailable')}return structuredClone(session)},
  async claimRun(input){e.claims.push(structuredClone(input));let run=claims.get(input.idempotencyKey);if(run){assert.equal(run.requestPayloadFingerprint,input.requestPayloadFingerprint);if(run.status==='failed'&&run.retryable&&run.attempt<run.maxAttempts){run.id=input.runId;run.status='running';run.attempt++;run.safeErrorCode=null;run.retryable=false;run.responseSchemaVersion=null;run.responsePayload=null;run.completedAt=null;committed=false;return{owned:true,run:structuredClone(run)}}return{owned:false,run:structuredClone(run)}}run={id:input.runId,sessionId:input.sessionId,userId:input.userId,stage:'agent',status:'running',idempotencyKey:input.idempotencyKey,attempt:1,maxAttempts:input.maxAttempts,requestSchemaVersion:input.requestSchemaVersion,responseSchemaVersion:null,requestPayloadFingerprint:input.requestPayloadFingerprint,responsePayload:null,model:input.model,promptVersion:input.promptVersion,safeErrorCode:null,retryable:false,startedAt:'2026-01-01T00:00:00Z',completedAt:null,updatedAt:'2026-01-01T00:00:00Z'};claims.set(input.idempotencyKey,run);session.runs.push(run);return{owned:true,run:structuredClone(run)}},
  async appendPipelineTurn(input){e.append++;if(appendFault==='precommit'&&fault){fault--;throw new Error('append precommit')}session.transcript.push(structuredClone(input.actorTurn),structuredClone(input.agentTurn));if(input.actorTurn?.kind==='answer')session.substantiveAnswerCount++;const run=session.runs.find(x=>x.id===input.agentRunId);assert.ok(run);Object.assign(run,{status:'completed',responseSchemaVersion:'agent-turn.v1',responsePayload:structuredClone(input.responsePayload),model:input.model,promptVersion:input.promptVersion,safeErrorCode:null,retryable:false,completedAt:'2026-01-01T00:00:01Z',updatedAt:'2026-01-01T00:00:01Z'});committed=true;if(appendFault==='commit-throw'&&fault){fault--;throw new Error('append response lost')}},
  async failRun(input){e.fail++;e.failInputs.push(structuredClone(input));const run=session.runs.find(x=>x.id===input.runId);if(!run||run.status!=='running')throw new Error('run_not_running');Object.assign(run,{status:'failed',safeErrorCode:input.safeErrorCode,retryable:input.retryable,completedAt:'2026-01-01T00:00:02Z'})},
  async confirmObservation(input){const o=session.observations.find(x=>x.id===input.observationId);o.confirmationState=input.state;o.blockedForQuestioning=input.state==='rejected';if(input.correction){session.corrections.push({id:input.correction.id,correctsObservationId:o.id,segment:{startMs:o.startMs,endMs:o.endMs},text:input.correction.text,correctionByTurnId:input.correction.turnId});session.transcript.push({id:input.correction.turnId,sequence:session.transcript.length,role:'actor',kind:'actor_correction',content:input.correction.text,questionFocus:null,groundingStartMs:o.startMs,groundingEndMs:o.endMs,sourceObservationIds:[o.id],reportEvidenceSelected:false})}}
 };
 const service=createAiPipelineService({repository,createAiTransport:()=>({agent:async request=>{e.provider++;e.requests.push(structuredClone(request));return{action:'ask_followup',utterance:'next',evidence:{observationIds:[]},reportEvidence:{observationIds:[],answerTurnIds:[]},done:false,completionReason:null,reportReady:false,model:'agent-model',promptVersion:'acting-agent.prompt.v2'}}}),loadAiServiceConfig:()=>({}),requireCurrentAiProcessingConsent:async()=>{},getCurrentConsentVersions:async()=>({}),coachSessionService:{},createSupabaseAdminClient:()=>null,getAppConfig:()=>({video:{bucket:'practice-videos'}})});
 return{session,e,service};
};
const add=(service,answer,n,sub,total)=>service.addTurn(ids.session,ids.user,{answer,requestId:id(n),expectedSubstantiveAnswerCount:sub,expectedTotalConversationCount:total});
test('Agent append commit response loss recovers exact persisted turns',async()=>{
 const {session,e,service}=harness({appendFault:'commit-throw'});const out=await add(service,'answer',101,0,0);assert.equal(out.actorTurn.id,session.transcript[0].id);assert.equal(out.agentTurn.id,session.transcript[1].id);assert.deepEqual([e.provider,e.append,e.fail],[1,1,0]);assert.equal(session.runs[0].status,'completed');
});

test('Agent append precommit failure retries same request with a fresh run',async()=>{
 const {session,e,service}=harness({appendFault:'precommit'});await assert.rejects(add(service,'answer',102,0,0),x=>x?.status===503&&x?.code==='TURN_PERSISTENCE_FAILED');assert.equal(session.runs[0].status,'failed');assert.equal(session.runs[0].safeErrorCode,'TURN_PERSISTENCE_FAILED');assert.equal(session.runs[0].retryable,true);const firstId=e.failInputs[0].runId;assert.equal(e.failInputs[0].safeErrorCode,'TURN_PERSISTENCE_FAILED');assert.equal(e.failInputs[0].retryable,true);const out=await add(service,'answer',102,0,0);assert.equal(out.actorTurn.id,session.transcript[0].id);assert.deepEqual([e.provider,e.append,e.fail],[2,2,1]);assert.equal(e.claims.length,2);assert.deepEqual(e.claims.map(x=>x.idempotencyKey),[`answer:${id(102)}`,`answer:${id(102)}`]);assert.equal(e.claims[0].requestPayloadFingerprint,e.claims[1].requestPayloadFingerprint);assert.notEqual(e.claims[0].runId,e.claims[1].runId);assert.equal(firstId,e.claims[0].runId);assert.equal(session.runs[0].id,e.claims[1].runId);assert.equal(session.runs[0].attempt,2);assert.equal(session.runs[0].status,'completed');
});

test('Agent first post-append reload failure recovers exact persisted turns',async()=>{
 const {session,e,service}=harness({reloadFailures:1});const out=await add(service,'answer',103,0,0);assert.equal(e.failedReads,1);assert.equal(out.actorTurn.id,session.transcript[0].id);assert.equal(out.agentTurn.id,session.transcript[1].id);assert.deepEqual([e.provider,e.append,e.fail],[1,1,0]);
});

test('Agent double reload failure maps safe persistence failure and preserves commit',async()=>{
 const {session,e,service}=harness({reloadFailures:2});await assert.rejects(add(service,'answer',104,0,0),x=>x?.status===503&&x?.code==='TURN_PERSISTENCE_FAILED');assert.equal(e.failedReads,2);assert.deepEqual([e.provider,e.append,e.fail],[1,1,1]);assert.equal(e.failInputs[0].runId,session.runs[0].id);assert.equal(e.failInputs[0].safeErrorCode,'TURN_PERSISTENCE_FAILED');assert.equal(e.failInputs[0].retryable,true);assert.equal(session.runs[0].status,'completed');
});

test('Agent answer unknown and correction paths preserve exact progress counts',async()=>{
 const {session,e,service}=harness();await add(service,'answer',105,0,0);assert.deepEqual([session.substantiveAnswerCount,reportable(session)],[1,1]);await add(service,'unknown',106,1,1);assert.deepEqual([session.substantiveAnswerCount,reportable(session)],[1,2]);assert.equal(session.transcript[2].kind,'unknown');const before=[session.substantiveAnswerCount,reportable(session)];await service.confirmObservation(ids.session,ids.observation,ids.user,{state:'rejected',correction:'not that'});assert.equal(session.transcript.at(-1).kind,'actor_correction');assert.deepEqual([session.substantiveAnswerCount,reportable(session)],before);await add(service,'another answer',107,1,2);assert.deepEqual([session.substantiveAnswerCount,reportable(session)],[2,3]);assert.deepEqual([e.provider,e.append,e.fail],[3,3,0]);assert.deepEqual(e.requests.map(x=>x.substantiveAnswerCount),[1,1,2]);
});
