import assert from 'node:assert/strict';
import test from 'node:test';
import { createAiPipelineService } from '../src/server/ai-pipeline-service-core.js';
const ids={session:'00000000-0000-4000-8000-000000000101',user:'00000000-0000-4000-8000-000000000102',request:'00000000-0000-4000-8000-000000000103',summaryRun:'00000000-0000-4000-8000-000000000104',take:'00000000-0000-4000-8000-000000000105',obs:'00000000-0000-4000-8000-000000000106',answer:'00000000-0000-4000-8000-000000000107',agent:'00000000-0000-4000-8000-000000000108'};
const normalized={schemaVersion:'scene-summary.v1',subtextStatus:'not_provided',observation:{timeline:'t',dialogue:'d',tempo:'t',pitch:'p',movement:'m',expression:'e',emotion:'e',extra:[]},summary:'s',intentAlignment:null,keyMoment:null,keyDimension:null,anomalies:[]};
const base=()=>({sessionId:ids.session,userId:ids.user,pipelineVersion:'ai-pipeline.v1',requiredConsentVersionSnapshot:'v1',aiProcessingConsentVersionSnapshot:'v1',interviewStatus:'active',completionReason:null,substantiveAnswerCount:0,reportEvidenceObservationIds:[],reportEvidenceAnswerTurnIds:[],sceneContext:{genre:'drama',situation:'scene',characterContext:'actor',subtext:null},take:{id:ids.take,storageBucket:'practice-videos',storagePath:'u/s/video.mp4',durationMs:1000,mediaMetadataVersion:'iso-bmff-duration.v1'},summary:{sourceRunId:ids.summaryRun,normalizedSummary:normalized},observations:[],corrections:[],transcript:[],runs:[],report:null});
const common=(repository,transport,extra={})=>({repository,createAiTransport:()=>transport,loadAiServiceConfig:()=>({}),requireCurrentAiProcessingConsent:async()=>{},getCurrentConsentVersions:async()=>({requiredConsentVersion:'v1',aiProcessingConsentVersion:'v1'}),coachSessionService:{},createSupabaseAdminClient:()=>({storage:{from:()=>({createSignedUrl:async()=>({data:{signedUrl:'https://signed.invalid'},error:null})})}}),getAppConfig:()=>({video:{bucket:'practice-videos',signedUrlExpiresInSeconds:60}}),createSummaryNetworkError:()=>new Error('network'),...extra});
const createBody={sessionId:ids.session,uploadIntentId:'00000000-0000-4000-8000-000000000140',storagePath:'u/s/video.mp4',genre:'drama',situation:'scene',characterContext:'actor',subtext:null};
function terminal(){const s=base();s.interviewStatus='completed';s.completionReason='manual_stop_report_ready';s.substantiveAnswerCount=1;s.observations=[{id:ids.obs,candidateId:ids.obs,sourceRunId:ids.summaryRun,confirmationState:'accepted',blockedForQuestioning:false,priority:1,startMs:0,endMs:1,text:'evidence',dimension:'voice',severity:'mid'}];s.reportEvidenceObservationIds=[ids.obs];s.reportEvidenceAnswerTurnIds=[ids.answer];s.transcript=[{id:ids.answer,sequence:0,role:'actor',kind:'answer',content:'answer',questionFocus:null,groundingStartMs:null,groundingEndMs:null,sourceObservationIds:[],reportEvidenceSelected:true}];s.runs=[{id:ids.agent,stage:'agent',status:'completed',responseSchemaVersion:'agent-turn.v1',model:'agent-model',promptVersion:'acting-agent.prompt.v2',attempt:1,completedAt:'2026-01-01T00:00:00Z',responsePayload:{actorTurn:null,agentTurn:{id:'00000000-0000-4000-8000-000000000109',sequence:1,role:'agent',kind:'closing',content:'done',questionFocus:null,groundingStartMs:null,groundingEndMs:null,sourceObservationIds:[],reportEvidenceSelected:false},done:true,completionReason:'manual_stop_report_ready',reportReady:true,reportEvidence:{observationIds:[ids.obs],answerTurnIds:[ids.answer]}}}];return s;}
const confirmed={status:'confirmed',content:'grounded',observationEvidenceIds:[ids.obs],turnEvidenceIds:[ids.answer],timestampRange:null};
const sections={oneLineSummary:confirmed,primaryReviewPoint:{...confirmed,turnEvidenceIds:[],timestampRange:{startMs:0,endMs:1}},confirmedEvidence:confirmed,actorDiscovery:{...confirmed,observationEvidenceIds:[]},groundedEncouragement:{...confirmed,turnEvidenceIds:[]},nextPracticeStep:confirmed};
const reportResponse=(runId)=>({schemaVersion:'report.v1',sessionId:ids.session,runId,model:'report-model',promptVersion:'acting-report.prompt.v2',sections});

test('summary precommit then same-key retry',async()=>{const session=base();session.summary=null;session.runs=[];let current=null,providers=0,completes=0,fails=0;const keys=[],fps=[],runIds=[];const repository={async findEligibleUpload(){return{sessionId:ids.session,storagePath:'u/s/video.mp4',requiredConsentVersionSnapshot:'v1',aiProcessingConsentVersionSnapshot:'v1'}},async createPipelineSession(){},async findPipelineSessionForOwner(){return structuredClone(session)},async claimRun(input){keys.push(input.idempotencyKey);fps.push(input.requestPayloadFingerprint);runIds.push(input.runId);if(!current){current={id:input.runId,stage:'summary',status:'running',attempt:1,maxAttempts:2,idempotencyKey:input.idempotencyKey,safeErrorCode:null,retryable:false};session.runs=[current]}else{assert.equal(current.status,'failed');assert.equal(current.retryable,true);assert.notEqual(input.runId,current.id);current={...current,id:input.runId,status:'running',attempt:2,safeErrorCode:null,retryable:false};session.runs=[current]}return{owned:true,run:structuredClone(current)}},async completeSummaryRun(input){completes++;if(completes===1)throw new Error('precommit');session.summary={sourceRunId:input.runId,normalizedSummary:structuredClone(input.normalizedSummary)};Object.assign(current,{status:'completed',responseSchemaVersion:'summary-response.v1',model:input.model,promptVersion:input.promptVersion})},async failRun(input){fails++;assert.equal(input.runId,current.id);assert.equal(input.safeErrorCode,'SUMMARY_PERSISTENCE_FAILED');assert.equal(input.retryable,true);Object.assign(current,{status:'failed',safeErrorCode:input.safeErrorCode,retryable:true})}};const service=createAiPipelineService(common(repository,{summary:async()=>{providers++;return{normalizedSummary:normalized,observationCandidates:[],model:'summary-model',promptVersion:'acting-summary.prompt.v2'}}}));await assert.rejects(service.createSession(createBody,ids.user),e=>e.status===503&&e.code==='SUMMARY_PERSISTENCE_FAILED');const result=await service.createSession(createBody,ids.user);assert.equal(result.summaryRun.status,'completed');assert.equal(providers,2);assert.equal(completes,2);assert.equal(fails,1);assert.deepEqual(keys,[keys[0],keys[0]]);assert.deepEqual(fps,[fps[0],fps[0]]);assert.notEqual(runIds[0],runIds[1]);});

test('report precommit then same-key retry',async()=>{const session=terminal();let current=null,providers=0,completes=0,fails=0;const keys=[],fps=[],idsSeen=[];const repository={async findPipelineSessionForOwner(){return structuredClone(session)},async claimRun(input){keys.push(input.idempotencyKey);fps.push(input.requestPayloadFingerprint);idsSeen.push(input.runId);if(!current){current={id:input.runId,stage:'report',status:'running',attempt:1,maxAttempts:2,idempotencyKey:input.idempotencyKey,safeErrorCode:null,retryable:false};session.runs.push(current)}else{assert.equal(current.status,'failed');assert.equal(current.retryable,true);const idx=session.runs.indexOf(current);current={...current,id:input.runId,status:'running',attempt:2,safeErrorCode:null,retryable:false};session.runs[idx]=current}return{owned:true,run:structuredClone(current)}},async completeReportRun(input){completes++;if(completes===1)throw new Error('precommit');Object.assign(current,{status:'completed',responseSchemaVersion:'report.v1',model:input.model,promptVersion:input.promptVersion,responsePayload:reportResponse(input.runId)});session.report={sessionId:ids.session,sourceRunId:input.runId,schemaVersion:'report.v1',completionReason:session.completionReason,...sections,createdAt:'now'}},async failRun(input){fails++;assert.equal(input.runId,current.id);assert.equal(input.safeErrorCode,'REPORT_PERSISTENCE_FAILED');assert.equal(input.retryable,true);Object.assign(current,{status:'failed',safeErrorCode:input.safeErrorCode,retryable:true})},async findImmutableReport(){return structuredClone(session.report)}};const service=createAiPipelineService(common(repository,{report:async(req)=>{providers++;return reportResponse(req.runId)}}));await assert.rejects(service.retryReport(ids.session,ids.user),e=>e.status===503&&e.code==='REPORT_PERSISTENCE_FAILED');const result=await service.retryReport(ids.session,ids.user);assert.equal(result.sourceRunId,current.id);assert.equal(providers,2);assert.equal(completes,2);assert.equal(fails,1);assert.deepEqual(keys,[`report:${ids.agent}`,`report:${ids.agent}`]);assert.deepEqual(fps,[fps[0],fps[0]]);assert.notEqual(idsSeen[0],idsSeen[1]);});

test('report commit response loss recovers immutable report',async()=>{const session=terminal();let providers=0,completes=0,fails=0,current;const repository={async findPipelineSessionForOwner(){return structuredClone(session)},async claimRun(input){current={id:input.runId,stage:'report',status:'running',attempt:1,maxAttempts:2,idempotencyKey:input.idempotencyKey,safeErrorCode:null};session.runs.push(current);return{owned:true,run:structuredClone(current)}},async completeReportRun(input){completes++;Object.assign(current,{status:'completed',responseSchemaVersion:'report.v1',model:input.model,promptVersion:input.promptVersion,responsePayload:reportResponse(input.runId)});session.report={sessionId:ids.session,sourceRunId:input.runId,schemaVersion:'report.v1',completionReason:session.completionReason,...sections,createdAt:'now'};throw new Error('commit response lost')},async failRun(){fails++},async findImmutableReport(){return structuredClone(session.report)}};const service=createAiPipelineService(common(repository,{report:async(req)=>{providers++;return reportResponse(req.runId)}}));const result=await service.retryReport(ids.session,ids.user);assert.deepEqual(result,session.report);assert.equal(providers,1);assert.equal(completes,1);assert.equal(fails,0);});

