import assert from "node:assert/strict";
import test from "node:test";
import {readFileSync} from "node:fs";
import path from "node:path";
import {createAiPipelineService} from "../src/server/ai-pipeline-service-core.js";
const root=path.resolve(import.meta.dirname,"..");const read=p=>readFileSync(path.join(root,p),"utf8");
const id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const aggregate=()=>({sessionId:id(1),userId:id(2),pipelineVersion:"ai-pipeline.v1",requiredConsentVersionSnapshot:"v1",aiProcessingConsentVersionSnapshot:"v1",interviewStatus:"completed_without_report",completionReason:"insufficient_interview_evidence",substantiveAnswerCount:0,reportEvidenceObservationIds:[],reportEvidenceAnswerTurnIds:[],summary:null,sceneContext:{genre:"g",situation:"s",characterContext:"c",subtext:null},take:{id:id(3),storageBucket:"practice-videos",storagePath:"u/s/v.mp4",durationMs:1,mediaMetadataVersion:"iso-bmff-duration.v1"},observations:[],corrections:[],transcript:[],runs:[],optionalNote:null,report:null});
const deps=repository=>({repository,createAiTransport:()=>({}),loadAiServiceConfig:()=>({}),requireCurrentAiProcessingConsent:async()=>{},getCurrentConsentVersions:async()=>({}),coachSessionService:{},createSupabaseAdminClient:()=>null,getAppConfig:()=>({video:{bucket:"practice-videos"}})});

test("optional note service trims, saves, replays, clears, reloads and exposes no turn id",async()=>{const session=aggregate();const writes=[];const repository={async findPipelineSessionForOwner(){return structuredClone(session)},async saveOptionalNote(input){writes.push(structuredClone(input));session.optionalNote=input.content;session.transcript=input.content?[{id:writes[0].turnId,sequence:0,role:"actor",kind:"optional_note",content:input.content,questionFocus:null,groundingStartMs:null,groundingEndMs:null,sourceObservationIds:[],reportEvidenceSelected:false}]:[]}};const service=createAiPipelineService(deps(repository));assert.deepEqual(await service.saveOptionalNote(id(1),id(2),{content:"  기억할 문장  "}),{optionalNote:"기억할 문장"});assert.match(writes[0].turnId,/^[0-9a-f-]{36}$/);const originalId=writes[0].turnId;assert.deepEqual(await service.saveOptionalNote(id(1),id(2),{content:"기억할 문장"}),{optionalNote:"기억할 문장"});assert.notEqual(writes[1].turnId,originalId);assert.deepEqual(await service.getSession(id(1),id(2)),session);assert.deepEqual(await service.saveOptionalNote(id(1),id(2),{content:"   "}),{optionalNote:null});assert.deepEqual(await service.saveOptionalNote(id(1),id(2),{content:null}),{optionalNote:null});assert.equal("turnId" in (await service.saveOptionalNote(id(1),id(2),{content:null})),false);});

test("optional note validation and malformed projection fail closed",async()=>{const session=aggregate();const repository={async findPipelineSessionForOwner(){return structuredClone(session)},async saveOptionalNote(){}};const service=createAiPipelineService(deps(repository));await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:1}),e=>e.code==="INVALID_OPTIONAL_NOTE");await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:"x".repeat(1001)}),e=>e.code==="INVALID_OPTIONAL_NOTE");delete session.optionalNote;await assert.rejects(service.getSession(id(1),id(2)),e=>e.code==="OPTIONAL_NOTE_PROJECTION_INVALID");});

test("optional note exact body visibility and terminal pairing fail closed",async()=>{let session=aggregate();const repository={async findPipelineSessionForOwner(){return session?structuredClone(session):null},async saveOptionalNote(){throw new Error("must not write")}};const service=createAiPipelineService(deps(repository));for(const body of [{},{content:null,extra:true}])await assert.rejects(service.saveOptionalNote(id(1),id(2),body),e=>e.status===400);session.interviewStatus="active";session.completionReason=null;await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:"x"}),e=>e.status===409);session.interviewStatus="paused";session.completionReason="manual_stop_paused";await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:"x"}),e=>e.status===409);session.interviewStatus="completed";session.completionReason="insufficient_interview_evidence";await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:"x"}),e=>e.status===409);session=null;await assert.rejects(service.saveOptionalNote(id(1),id(2),{content:"x"}),e=>e.status===404);});

test("optional note leaves Report fingerprint and provider request unchanged",async()=>{const normalized={schemaVersion:"scene-summary.v1",subtextStatus:"not_provided",observation:{timeline:"t",dialogue:"d",tempo:"t",pitch:"p",movement:"m",expression:"e",emotion:"e",extra:[]},summary:"s",intentAlignment:null,keyMoment:null,keyDimension:null,anomalies:[]};const answer={id:id(10),sequence:0,role:"actor",kind:"answer",content:"answer",questionFocus:null,groundingStartMs:null,groundingEndMs:null,sourceObservationIds:[],reportEvidenceSelected:true};const observation={id:id(11),candidateId:id(11),sourceRunId:id(12),confirmationState:"accepted",blockedForQuestioning:false,priority:1,startMs:0,endMs:1,text:"evidence",dimension:"voice",severity:"mid"};const terminal={id:id(13),stage:"agent",status:"completed",responseSchemaVersion:"agent-turn.v1",model:"agent",promptVersion:"acting-agent.prompt.v2",completedAt:"2026-01-01T00:00:00Z",attempt:1,responsePayload:{actorTurn:null,agentTurn:{...answer,id:id(14),sequence:1,role:"agent",kind:"closing",content:"done",questionFocus:null,reportEvidenceSelected:false},done:true,completionReason:"hard_limit_report_ready",reportReady:true,reportEvidence:{observationIds:[id(11)],answerTurnIds:[id(10)]}}};const captures=[];for(const withNote of [false,true]){const session={...aggregate(),interviewStatus:"completed",completionReason:"hard_limit_report_ready",summary:{sourceRunId:id(12),normalizedSummary:normalized},observations:[observation],transcript:[answer],reportEvidenceObservationIds:[id(11)],reportEvidenceAnswerTurnIds:[id(10)],runs:[terminal]};if(withNote){session.optionalNote="private note";session.transcript.push({id:id(15),sequence:1,role:"actor",kind:"optional_note",content:"private note",questionFocus:null,groundingStartMs:null,groundingEndMs:null,sourceObservationIds:[],reportEvidenceSelected:false});}let fingerprint,request;const repository={async findPipelineSessionForOwner(){return structuredClone(session)},async claimRun(input){fingerprint=input.requestPayloadFingerprint;return{owned:true,run:{id:input.runId,stage:"report",status:"running"}}},async failRun(){}};const service=createAiPipelineService({...deps(repository),createAiTransport:()=>({report:async value=>{request=structuredClone(value);throw new Error("stop")}})});await assert.rejects(service.retryReport(id(1),id(2)));captures.push({fingerprint,request:{...request,runId:"normalized"}});}assert.equal(captures[0].fingerprint,captures[1].fingerprint);assert.deepEqual(captures[0].request,captures[1].request);});

test("migration010 locks terminal owner transcript and owns exact optional-note invariants",()=>{const sql=read("../../supabase/migrations/010_ai_pipeline_optional_note.sql");for(const pattern of [/interview_turns_optional_note_shape_check/,/interview_turns_one_optional_note_per_session_idx/,/p_turn_id uuid/,/security definer set search_path=pg_catalog,public/,/hidden_at is not null/,/deletion_status <> 'active'/,/for update/,/non_contiguous_transcript/,/optional_note_not_last/,/length\(normalized\) > 1000/,/grant execute.*service_role/,/revoke all.*public, anon, authenticated/])assert.match(sql,pattern);assert.match(sql,/insert into public\.interview_turns\(id[\s\S]*values\(p_turn_id/);});

test("route client DTO OpenAPI and terminal accessible UI expose exact content-only surface",()=>{const route=read("src/app/api/v1/practice-sessions/[sessionId]/optional-note/route.ts"),client=read("src/lib/api/practice.ts"),types=read("src/lib/api/types.ts"),ui=read("src/features/practice/pipeline/session-detail.tsx"),openapi=JSON.parse(read("src/lib/api/openapi.json"));assert.match(route,/export async function PUT/);assert.match(route,/saveOptionalNote\(sessionId,auth\.userId/);assert.match(client,/savePipelineOptionalNote/);assert.match(client,/"PUT"/);assert.match(types,/SavePipelineOptionalNoteResponse = \{ optionalNote: string \| null \}/);assert.deepEqual(openapi.components.schemas.SavePipelineOptionalNoteResponse.required,["optionalNote"]);assert.equal(openapi.components.schemas.SavePipelineOptionalNoteRequest.additionalProperties,false);assert.equal(openapi.components.schemas.SavePipelineOptionalNoteRequest.properties.content.maxLength,1000);assert.match(openapi.components.schemas.SavePipelineOptionalNoteRequest.properties.content.description,/공백 문자열/);assert.deepEqual(Object.keys(openapi.paths["/api/v1/practice-sessions/{sessionId}/optional-note"].put.responses),["200","400","401","403","404","409","503"]);assert.match(ui,/내 문장 남기기 \(선택\)/);assert.match(ui,/aria-live="polite"/);assert.match(ui,/내 문장을 저장했어요/);assert.match(ui,/내 문장을 지웠어요/);assert.match(ui,/htmlFor="optional-note"/);assert.match(ui,/completed_without_report/);assert.match(ui,/persistOptionalNote\(null\)/);assert.doesNotMatch(route,/createSummary|finalActorSentence/);});

test("one provider transcript helper excludes optional_note from Agent and Report inputs",()=>{const core=read("src/server/ai-pipeline-service-core.js");assert.match(core,/const providerTranscript = \(session\) => session\.transcript[\s\S]*kind !== "optional_note"/);assert.equal((core.match(/transcript: providerTranscript\(session\)/g)??[]).length,3);assert.doesNotMatch(core,/reportClaimPayload[\s\S]*session\.transcript\.map/);});
