#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

#
# ── 이 wizard 가 하는 일 ──────────────────────────────────────────────────
# 홈서버(insung-server)가 docker compose 배포를 받을 수 있게 준비하는 8단계를
# 사람과 함께 밟는다. 스크립트가 직접 하는 것은 **안내와 검증뿐**이다 — 서버를
# 바꾸는 명령(sudo)·Tailscale/Cloudflare/AWS 대시보드 작업은 사람이 하고,
# 스크립트는 그 결과를 읽기 전용 명령으로 확인한다.
#
#   deploy/home/prepare-server.sh            # 대화형. 순서대로 안내하고 검증한다
#   deploy/home/prepare-server.sh --check    # 검증만. 묻지 않고 8단계 상태를 보고한다
#                                            # (남은 단계가 있으면 exit≠0)
#
# 이 맥에서 실행한다. 서버 확인은 `ssh <계정>@insung-server '<읽기 명령>'`(Tailscale
# SSH)로 한다. Tailscale 접근 규칙이 재확인 방식(ACL 의 action "check")이라 첫 접속에
# 브라우저 링크가 뜰 수 있다 — 열어서 승인하면 이어진다(--check 모드도 그때는 기다린다).
#
# 시크릿 값은 화면·로그에 찍지 않는다 — .env 의 시크릿은 키 유무·권한만 보고, AWS 키만
# 검증(get-caller-identity·버킷 목록)을 위해 맥의 셸 변수로 잠깐 가져온다. 유일한 쓰기는
# 3단계의 GitHub secrets(gh) 다 — 서버가 아니라 레포 설정이고, 값을 화면에 안 찍으려고
# 스크립트가 넣는다. GitHub 웹에서 직접 넣어도 된다.
#
# 각 단계는 먼저 검증하고, 이미 되어 있으면 안내 없이 지나간다. 그래서 중간에 끊고
# 다시 돌려도 된 단계는 빠르게 통과한다. 서버·계정 이름은 환경변수로 바꿀 수 있다
# (아래 STAGES 절의 기본값 참조). .env 키 목록은 deploy/home/compose.yml 과
# deploy/home/.env.example 이 정본이다 — 목록이 어긋나면 이 파일이 아니라 그쪽을 믿는다.
#
# 라이브러리(아래 `set -euo pipefail` 부터 STAGES 표시까지)는 wizard 스킬 템플릿
# 그대로다. 손대지 않는다.
set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — 홈서버 준비 8단계. 여기부터가 이 wizard 고유의 내용이다.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

SERVER_HOST="${SERVER_HOST:-insung-server}"          # Tailscale MagicDNS 이름
ADMIN_USER="${ADMIN_USER:-insung}"                    # sudo 가 되는 사람 계정
DEPLOY_USER="${DEPLOY_USER:-deploy}"                  # 배포 전용 계정(docker 그룹, sudo 없음)
SVC_ROOT="${SVC_ROOT:-/svc/acttub}"                   # 프로젝트 디렉터리 $SVC_ROOT/{dev,prod}
DEV_TEMP_HOST="${DEV_TEMP_HOST:-dev-home.acttub.com}" # dev 스모크용 임시 호스트명
BACKUP_BUCKET="${BACKUP_BUCKET:-acttub-db-backups}"   # 매일 pg_dump 가 가는 버킷
AWS_SSO_PROFILE="${AWS_SSO_PROFILE:-acttub}"          # 수명주기 확인에만 쓰는 관리자 프로필
DOCKER_MIN="${DOCKER_MIN:-29.7}"                      # apt upgrade 가 올려야 하는 docker 하한
ENVS="dev prod"
export GH_REPO="${GH_REPO:-acttub/acttub-platform}"   # gh secret 이 향하는 레포

# 이 wizard 는 로컬 .env 를 쓰지 않는다 — .env 는 서버에만 있고 사람이 쓴다.
# 라이브러리의 ask/ask_secret 이 기본값을 찾으러 여기를 보지만 파일이 아니라 아무것도 없다.
ENV_FILE=/dev/null

# .env 키. 정본은 deploy/home/compose.yml(${VAR:?} 로 요구하는 것)과 deploy/home/.env.example 이다.
# DATABASE_URL 은 적지 않는다 — compose 가 POSTGRES_PASSWORD 로 조립한다.
# TUNNEL_TOKEN(cloudflared)·BACKUP_BUCKET(backup)은 그 서비스가 compose 에 아직 없어도 이 준비에서
# 넣으므로 필수로 본다. 선택 키는 비어 있으면 경고만 한다.
REQUIRED_ENV_KEYS="COMPOSE_PROJECT_NAME POSTGRES_PASSWORD JWT_SECRET ADMIN_OPS_TOKEN GEMINI_API_KEY OPENAI_API_KEY S3_BUCKET AWS_REGION AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY TUNNEL_TOKEN BACKUP_BUCKET"
OPTIONAL_ENV_KEYS="SENTRY_DSN SENTRY_ENVIRONMENT APPLE_OAUTH_CLIENT_ID GOOGLE_OAUTH_CLIENT_ID"

CURRENT_STAGE=""

# ── 출력 보조 ─────────────────────────────────────────────────────────────
ok()  { printf '  %s✔ %s%s\n' "$GREEN" "$1" "$RESET"; }
bad() { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
# cmd LINE... — 사람이 붙여 넣을 명령. 스크립트는 이것을 실행하지 않는다.
cmd() { local l; for l in "$@"; do printf '      %s%s%s\n' "$BOLD" "$l" "$RESET"; done; }
# nth_line TEXT N — TEXT 의 N 번째 줄
nth_line() { printf '%s\n' "$1" | sed -n "${2}p"; }
strip_quotes() { local v="$1"; v="${v%\"}"; v="${v#\"}"; v="${v%\'}"; v="${v#\'}"; printf '%s' "$v"; }
# version_at_least A B — A ≥ B (숫자 마디 비교). 맥의 sort 에는 -V 가 없어 awk 로 센다.
version_at_least() {
  awk -v a="$1" -v b="$2" 'BEGIN {
    na = split(a, x, "."); nb = split(b, y, "."); n = (na > nb) ? na : nb
    for (i = 1; i <= n; i++) { p = x[i] + 0; q = y[i] + 0; if (p > q) exit 0; if (p < q) exit 1 }
    exit 0 }'
}
deploy_ssh_failed() { bad "$1: ssh ${DEPLOY_USER}@${SERVER_HOST} 실패 (2·3단계가 먼저입니다)"; }

# ── 서버 읽기 ─────────────────────────────────────────────────────────────
# on_server USER 'cmd' — 서버에서 읽기 전용 명령을 돌리고 stdout 을 돌려준다.
# 바꾸는 명령(sudo·chown·파일 쓰기)은 여기로 보내지 않는다 — 그건 사람이 한다.
# stderr 는 그대로 둔다: Tailscale 의 브라우저 확인 링크가 거기로 나온다.
# -n 으로 로컬 stdin 을 넘기지 않는다 — 안 그러면 ssh 가 사람이 치는 답(Enter·s)을 삼킨다.
# 원격 로그인 셸이 stdout 에 무언가 찍어도(.bashrc 의 echo 등) 줄 번호가 밀리지 않도록
# 표식 줄을 먼저 찍고 그 뒤만 돌려준다. 종료 코드는 pipefail 로 ssh 의 것이 남는다.
on_server() {
  local user="$1" script="$2"
  ssh -n -o ConnectTimeout=15 -o StrictHostKeyChecking=accept-new "${user}@${SERVER_HOST}" -- \
    "echo __WIZARD_BEGIN__; $script" | sed -n '/^__WIZARD_BEGIN__$/,$p' | sed 1d
}

# env_file_state ENV KEY... — 서버의 $SVC_ROOT/ENV/.env 를 deploy 계정으로 본다.
# 첫 줄: "소유자 권한" 또는 MISSING(파일 없음). 둘째 줄에 UNREADABLE 이 오면 deploy 가 못 읽는
# 파일이다(root 소유 600 등). 이어서 값이 빈 키마다 "MISSING 키" 한 줄. 값은 절대 돌려주지 않는다.
env_file_state() {
  local e="$1"; shift
  on_server "$DEPLOY_USER" "
    f='$SVC_ROOT/$e/.env'
    stat -c '%U %a' \"\$f\" 2>/dev/null || { echo MISSING; exit 0; }
    test -r \"\$f\" || { echo UNREADABLE; exit 0; }
    for k in $*; do grep -qE \"^\$k=.+\" \"\$f\" || echo \"MISSING \$k\"; done
  "
}

# read_env_values ENV KEY... — 값을 키 순서대로 한 줄씩 돌려준다(없으면 빈 줄).
# 시크릿이 지나가는 유일한 길이다. 결과를 화면에 찍지 말 것.
read_env_values() {
  local e="$1"; shift
  on_server "$DEPLOY_USER" "
    f='$SVC_ROOT/$e/.env'
    for k in $*; do
      v=\$(grep -E \"^\$k=\" \"\$f\" 2>/dev/null | tail -n1 | cut -d= -f2- | tr -d '\r')
      printf '%s\n' \"\$v\"
    done
  "
}

# aws_with AK SK REGION <aws 인자> — .env 의 키로만 부른다. SSO 프로필·세션 토큰은 지운다.
# 서브셸에서 export 한다 — `env K=V aws` 로 넘기면 그 순간 ps 의 인자 목록에 키가 보인다.
aws_with() {
  local ak="$1" sk="$2" region="$3"; shift 3
  (
    unset AWS_PROFILE AWS_DEFAULT_PROFILE AWS_SESSION_TOKEN
    export AWS_ACCESS_KEY_ID="$ak" AWS_SECRET_ACCESS_KEY="$sk" AWS_DEFAULT_REGION="${region:-ap-northeast-2}"
    exec aws --no-cli-pager "$@"
  )
}

# server_tags — 이 맥의 tailscale 이 보는 서버의 태그(한 줄에 하나)
server_tags() {
  local ts
  ts=$(command -v tailscale 2>/dev/null || echo /Applications/Tailscale.app/Contents/MacOS/Tailscale)
  "$ts" status --json 2>/dev/null | jq -r --arg h "$SERVER_HOST" '
    [.Peer[]?] | map(select(.HostName == $h or (.DNSName | startswith($h + ".")))) | .[0] | (.Tags // [])[]' 2>/dev/null
}

gh_has_secret() { gh secret list 2>/dev/null | awk '{print $1}' | grep -qx "$1"; }

# ── 1. 재부팅(커널)·docker 업그레이드 ─────────────────────────────────────
verify_reboot_docker() {
  local out failed=0 kernel reboot dver upg rag containers
  out=$(on_server "$ADMIN_USER" '
    uname -r
    if [ -f /var/run/reboot-required ]; then echo REBOOT_REQUIRED; else echo REBOOT_CLEAR; fi
    docker version --format "{{.Server.Version}}" 2>/dev/null || echo DOCKER_DOWN
    apt list --upgradable 2>/dev/null | grep -E "^(docker-ce|docker-ce-cli|docker-compose-plugin|docker-buildx-plugin|containerd\.io)/" | cut -d/ -f1 | tr "\n" " "; echo
    systemctl is-active acttub-rag 2>/dev/null || true
    docker ps -q 2>/dev/null | wc -l | tr -d " "
  ') || { bad "서버에 접속하지 못했습니다: ssh ${ADMIN_USER}@${SERVER_HOST} (재부팅 중이면 1~2분 뒤 다시)"; return 1; }
  kernel=$(nth_line "$out" 1); reboot=$(nth_line "$out" 2); dver=$(nth_line "$out" 3)
  upg=$(nth_line "$out" 4); rag=$(nth_line "$out" 5); containers=$(nth_line "$out" 6)
  say "커널 $kernel"
  if [[ "$reboot" == REBOOT_CLEAR ]]; then ok "재부팅 대기 없음 (/var/run/reboot-required 없음)"
  else bad "재부팅이 필요합니다 (/var/run/reboot-required 있음)"; failed=1; fi
  if [[ "$dver" == DOCKER_DOWN ]]; then bad "docker 데몬에 닿지 않습니다"; failed=1
  elif version_at_least "$dver" "$DOCKER_MIN"; then ok "docker $dver (하한 $DOCKER_MIN)"
  else bad "docker $dver — $DOCKER_MIN 이상이어야 합니다 (apt upgrade)"; failed=1; fi
  # apt 목록은 마지막 apt update 기준이다. 그래서 위 버전 하한을 같이 본다.
  if [[ -z "${upg// /}" ]]; then ok "apt 에 docker 업그레이드 대기 없음 (마지막 apt update 기준)"
  else bad "업그레이드 대기: $upg"; failed=1; fi
  note "기존 서비스: acttub-rag=${rag:-?}, 컨테이너 ${containers:-?}개 (재부팅 뒤에도 같아야 합니다)"
  return "$failed"
}
guide_reboot_docker() {
  say "서버에 들어가 패키지를 올리고 재부팅합니다. 아래를 서버에서 그대로 붙여 넣으세요."
  cmd "ssh ${ADMIN_USER}@${SERVER_HOST}" \
      "sudo apt update && sudo apt upgrade -y" \
      "sudo reboot"
  note "재부팅에 1~2분. 그동안 여기서 확인하면 접속 실패로 나옵니다 — 기다렸다 다시 Enter."
  note "재부팅 뒤 acttub-rag 와 기존 컨테이너(hermes)가 다시 떴는지도 위 검증이 같이 보여 줍니다."
}

# ── 2. deploy 계정·디렉터리 ───────────────────────────────────────────────
verify_deploy_account() {
  local out failed=0 grp e val
  out=$(on_server "$ADMIN_USER" "
    id -nG '$DEPLOY_USER' 2>/dev/null || echo NO_USER
    for e in $ENVS; do printf '%s ' \"\$e\"; stat -c '%U %a' \"$SVC_ROOT/\$e\" 2>/dev/null || echo MISSING; done
  ") || { bad "서버에 접속하지 못했습니다: ssh ${ADMIN_USER}@${SERVER_HOST}"; return 1; }
  grp=$(nth_line "$out" 1)
  if [[ "$grp" == NO_USER ]]; then bad "계정 $DEPLOY_USER 가 없습니다"; failed=1
  else
    if printf '%s\n' "$grp" | tr ' ' '\n' | grep -qx docker; then ok "$DEPLOY_USER 는 docker 그룹"
    else bad "$DEPLOY_USER 가 docker 그룹에 없습니다"; failed=1; fi
    if printf '%s\n' "$grp" | tr ' ' '\n' | grep -qxE 'sudo|admin|wheel'; then bad "$DEPLOY_USER 에 sudo 가 있습니다 — 빼야 합니다"; failed=1
    else ok "$DEPLOY_USER 에 sudo 없음"; fi
  fi
  for e in $ENVS; do
    val=$(printf '%s\n' "$out" | awk -v e="$e" '$1 == e { $1 = ""; sub(/^ /, ""); print }')
    if [[ "$val" == MISSING || -z "$val" ]]; then bad "$SVC_ROOT/$e 가 없습니다"; failed=1
    elif [[ "${val%% *}" == "$DEPLOY_USER" ]]; then ok "$SVC_ROOT/$e 소유 $val"
    else bad "$SVC_ROOT/$e 소유자가 $DEPLOY_USER 가 아닙니다 (지금: $val)"; failed=1; fi
  done
  return "$failed"
}
guide_deploy_account() {
  say "배포 전용 계정과 프로젝트 디렉터리를 만듭니다. docker 그룹만 주고 sudo 는 주지 않습니다."
  cmd "sudo adduser --disabled-password --gecos '' $DEPLOY_USER" \
      "sudo usermod -aG docker $DEPLOY_USER" \
      "sudo mkdir -p $SVC_ROOT/dev $SVC_ROOT/prod" \
      "sudo chown $DEPLOY_USER:$DEPLOY_USER $SVC_ROOT/dev $SVC_ROOT/prod" \
      "sudo chmod 750 $SVC_ROOT/dev $SVC_ROOT/prod"
  note "docker 그룹은 root 와 같은 힘입니다(컨테이너에 호스트를 마운트할 수 있음). 그래서 이 계정으로는 배포만 합니다."
  note "Tailscale SSH 는 비밀번호·키가 필요 없습니다. 계정이 있고 3단계의 접근 규칙이 users 에 $DEPLOY_USER 를 허용하면 됩니다."
}

# ── 3. Tailscale — 규칙 → 태그 → 사람 SSH 재확인 → OAuth ───────────────────
verify_tailscale() {
  local failed=0 tags
  tags=$(server_tags || true)
  if printf '%s\n' "$tags" | grep -qx 'tag:homeserver'; then ok "서버 태그 tag:homeserver"
  else bad "서버에 tag:homeserver 가 없습니다 (이 맥의 tailscale status 기준)"; failed=1; fi
  if on_server "$ADMIN_USER" true >/dev/null; then ok "ssh ${ADMIN_USER}@${SERVER_HOST}"
  else bad "ssh ${ADMIN_USER}@${SERVER_HOST} 실패"; failed=1; fi
  if on_server "$DEPLOY_USER" true >/dev/null; then ok "ssh ${DEPLOY_USER}@${SERVER_HOST}"
  else bad "ssh ${DEPLOY_USER}@${SERVER_HOST} 실패 (2단계 계정, 접근 규칙의 users 목록 확인)"; failed=1; fi
  if gh_has_secret TS_OAUTH_CLIENT_ID && gh_has_secret TS_OAUTH_SECRET; then ok "GitHub secrets TS_OAUTH_CLIENT_ID·TS_OAUTH_SECRET ($GH_REPO)"
  else bad "GitHub secrets TS_OAUTH_CLIENT_ID·TS_OAUTH_SECRET 이 없습니다 ($GH_REPO)"; failed=1; fi
  return "$failed"
}
guide_tailscale() {
  local tags
  tags=$(server_tags || true)
  if ! printf '%s\n' "$tags" | grep -qx 'tag:homeserver'; then
    warn "순서를 지켜야 스스로 잠기지 않습니다. 태그가 붙는 순간 서버는 autogroup:self 에서 빠지므로,"
    warn "사람용 ssh 규칙이 먼저 있어야 합니다. 지금 열린 SSH 세션이 있으면 끝날 때까지 닫지 마세요."
    printf '\n'
    step "① 접근 규칙(ACL)에 tagOwners 와 ssh 규칙 둘을 추가하고 저장합니다."
    open_url "https://login.tailscale.com/admin/acls/file"
    cmd '"tagOwners": {' \
        '  "tag:homeserver": ["autogroup:admin"],' \
        '  "tag:ci":         ["autogroup:admin"]' \
        '},' \
        '"ssh": [' \
        '  // 기존 autogroup:self 규칙은 그대로 둔다 (다른 기기용)' \
        "  {\"action\": \"check\",  \"src\": [\"autogroup:member\"], \"dst\": [\"tag:homeserver\"], \"users\": [\"$ADMIN_USER\", \"$DEPLOY_USER\", \"root\"]}," \
        "  {\"action\": \"accept\", \"src\": [\"tag:ci\"],           \"dst\": [\"tag:homeserver\"], \"users\": [\"$DEPLOY_USER\"]}" \
        ']'
    note "check = 사람이 브라우저로 재확인. accept = 확인 없음(CI 노드는 브라우저를 못 엽니다)."
    note "acls/grants 가 기본(*→*:*)이 아니면 tag:ci → tag:homeserver:22 도 허용해야 합니다."
    if ! confirm "규칙을 저장했고 편집기에 오류가 없었나요?"; then
      warn "저장 뒤에 다시 오세요. 규칙 없이 태그를 붙이면 사람이 못 들어갑니다."
      return 0
    fi
    printf '\n'
    step "② 서버에 태그를 붙입니다: Machines → ${SERVER_HOST} → ⋯ → Edit ACL tags → tag:homeserver → Save"
    open_url "https://login.tailscale.com/admin/machines"
    note "태그 노드는 키 만료가 꺼집니다(따로 할 일 없음)."
    pause "태그를 붙였으면 Enter"
    printf '\n'
    step "③ 사람 SSH 재확인 — 아래 검증이 ${ADMIN_USER}·${DEPLOY_USER} 두 계정으로 접속합니다. 브라우저 링크가 뜨면 승인하세요."
    note "호스트 키가 바뀌었다는 오류가 나면: ssh-keygen -R ${SERVER_HOST}"
  else
    ok "①~③(규칙·태그·사람 SSH)은 되어 있습니다."
  fi
  if gh_has_secret TS_OAUTH_CLIENT_ID && gh_has_secret TS_OAUTH_SECRET; then
    ok "④ GitHub secrets 도 있습니다."
    return 0
  fi
  printf '\n'
  step "④ OAuth 클라이언트: Settings → OAuth clients → Generate OAuth client → Keys › Auth Keys: Write, Tags: tag:ci → Generate"
  open_url "https://login.tailscale.com/admin/settings/oauth"
  note "화면 문구가 다르면 'OAuth client 생성'과 'auth_keys 쓰기 권한 + tag:ci'를 찾으세요."
  note "Client ID 와 Client secret 을 여기 붙여 넣으면 gh 로 GitHub secrets 에 저장합니다(값은 화면에 남지 않음)."
  note "GitHub 웹에서 이미 넣었다면 빈 채로 Enter."
  # 이 스크립트의 유일한 쓰기다. 서버가 아니라 레포 시크릿이고, 값을 화면에 안 찍으려고
  # gh 로 넣는다. 사람이 GitHub 웹에서 넣어도 검증(gh secret list)은 같다.
  local TS_OAUTH_CLIENT_ID="" TS_OAUTH_SECRET=""
  ask_secret TS_OAUTH_CLIENT_ID "Client ID:"
  ask_secret TS_OAUTH_SECRET "Client secret:"
  if [[ -n "$TS_OAUTH_CLIENT_ID" && -n "$TS_OAUTH_SECRET" ]]; then
    set_secret TS_OAUTH_CLIENT_ID "$TS_OAUTH_CLIENT_ID"
    set_secret TS_OAUTH_SECRET "$TS_OAUTH_SECRET"
  elif [[ -n "$TS_OAUTH_CLIENT_ID$TS_OAUTH_SECRET" ]]; then
    warn "둘 다 있어야 저장합니다 — 하나만 받아서 저장하지 않았습니다."
  fi
}

# ── 4. Cloudflare Tunnel 둘 ──────────────────────────────────────────────
verify_tunnel() {
  local failed=0 e out code
  for e in $ENVS; do
    out=$(env_file_state "$e" TUNNEL_TOKEN) || { deploy_ssh_failed "$e"; failed=1; continue; }
    if [[ "$(nth_line "$out" 1)" == MISSING ]]; then bad "$e: $SVC_ROOT/$e/.env 가 없습니다"; failed=1
    elif [[ "$(nth_line "$out" 2)" == UNREADABLE ]]; then bad "$e: .env 를 $DEPLOY_USER 가 읽지 못합니다 (소유자 $(nth_line "$out" 1) — chown $DEPLOY_USER)"; failed=1
    elif printf '%s\n' "$out" | grep -q '^MISSING TUNNEL_TOKEN'; then bad "$e: .env 에 TUNNEL_TOKEN 이 없습니다"; failed=1
    else ok "$e: TUNNEL_TOKEN 있음"; fi
  done
  # dev 임시 호스트명이 터널로 가는지. 530 = 호스트명은 터널에 묶였지만 커넥터가 아직 없음(compose 전이라 정상).
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://${DEV_TEMP_HOST}/" || true)
  case "$code" in
    000)         bad "$DEV_TEMP_HOST 가 닿지 않습니다 (Public Hostname 미등록?)"; failed=1 ;;
    530)         ok "$DEV_TEMP_HOST → 터널에 연결됨 (HTTP 530 = 커넥터 미접속, compose 기동 전이라 정상)" ;;
    502|503|504) ok "$DEV_TEMP_HOST → 터널은 붙었지만 web 이 아직 없음 (HTTP $code)" ;;
    2*|3*)       ok "$DEV_TEMP_HOST 응답 중 (HTTP $code)" ;;
    *)           bad "$DEV_TEMP_HOST 가 예상 밖 응답 HTTP $code — 대시보드에서 호스트명·서비스(web:3000)를 확인하세요"; failed=1 ;;
  esac
  return "$failed"
}
guide_tunnel() {
  say "Cloudflare Zero Trust 에서 터널 둘을 만들고, 토큰을 서버 .env 의 TUNNEL_TOKEN 에 넣습니다."
  open_url "https://one.dash.cloudflare.com/"
  step "Networks → Tunnels → Create a tunnel → Cloudflared → 이름 acttub-dev → Save tunnel"
  step "다음 화면(커넥터 설치)의 명령 안에 있는 긴 토큰(eyJ… 로 시작)을 복사합니다. 설치 명령은 실행하지 않습니다 — compose 의 cloudflared 컨테이너가 대신 돕니다."
  step "Public Hostname 탭 → Add: Subdomain ${DEV_TEMP_HOST%%.*} · Domain ${DEV_TEMP_HOST#*.} · Type HTTP · URL web:3000 → Save"
  note "web:3000 은 compose 네트워크 안의 서비스 이름입니다. localhost 가 아닙니다."
  step "같은 방법으로 acttub-prod 도 만듭니다(호스트명은 아직 붙이지 않음 — 운영을 홈서버로 옮기는 날에)."
  note "메뉴 이름은 Cloudflare 가 가끔 바꿉니다. 'Tunnels' 가 안 보이면 Networks 아래를 찾으세요."
  printf '\n'
  say "토큰을 서버 .env 에 넣습니다($DEPLOY_USER 계정으로, 권한 600):"
  cmd "ssh ${DEPLOY_USER}@${SERVER_HOST}" \
      "umask 077" \
      "nano $SVC_ROOT/dev/.env      # TUNNEL_TOKEN=eyJ...  한 줄 (nano 가 없으면 vi)" \
      "nano $SVC_ROOT/prod/.env     # prod 터널의 토큰" \
      "chmod 600 $SVC_ROOT/dev/.env $SVC_ROOT/prod/.env"
}

# ── 5. AWS — IAM 사용자 둘·백업 버킷 ──────────────────────────────────────
print_iam_policy() {
  local e="$1"
  cmd '{' \
      '  "Version": "2012-10-17",' \
      '  "Statement": [' \
      '    {"Effect": "Allow", "Action": ["s3:PutObject", "s3:GetObject", "s3:DeleteObject"],' \
      "     \"Resource\": \"arn:aws:s3:::acttub-practice-videos-$e/*\"}," \
      '    {"Effect": "Allow", "Action": "s3:ListBucket",' \
      "     \"Resource\": \"arn:aws:s3:::acttub-practice-videos-$e\"}," \
      '    {"Effect": "Allow", "Action": ["s3:PutObject", "s3:GetObject"],' \
      "     \"Resource\": \"arn:aws:s3:::$BACKUP_BUCKET/$e/*\"}," \
      '    {"Effect": "Allow", "Action": "s3:ListBucket",' \
      "     \"Resource\": \"arn:aws:s3:::$BACKUP_BUCKET\"," \
      "     \"Condition\": {\"StringLike\": {\"s3:prefix\": [\"$e/*\"]}}}" \
      '  ]' \
      '}'
}
verify_aws() {
  local failed=0 e vals ak sk region bucket arn days
  for e in $ENVS; do
    vals=$(read_env_values "$e" AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION S3_BUCKET) \
      || { deploy_ssh_failed "$e"; failed=1; continue; }
    ak=$(strip_quotes "$(nth_line "$vals" 1)"); sk=$(strip_quotes "$(nth_line "$vals" 2)")
    region=$(strip_quotes "$(nth_line "$vals" 3)"); bucket=$(strip_quotes "$(nth_line "$vals" 4)")
    if [[ -z "$ak" || -z "$sk" ]]; then bad "$e: .env 에 AWS_ACCESS_KEY_ID·AWS_SECRET_ACCESS_KEY 가 없습니다"; failed=1; continue; fi
    if ! arn=$(aws_with "$ak" "$sk" "$region" sts get-caller-identity --query Arn --output text 2>/dev/null); then
      bad "$e: 그 키로 get-caller-identity 실패 (키가 틀리거나 비활성)"; failed=1; continue
    fi
    case "$arn" in
      *":user/acttub-home-$e") ok "$e: 키의 주인 ${arn##*:}" ;;
      *) bad "$e: 키의 주인이 acttub-home-$e 가 아닙니다 (${arn##*:})"; failed=1 ;;
    esac
    [[ -z "$bucket" ]] && bucket="acttub-practice-videos-$e"
    if aws_with "$ak" "$sk" "$region" s3api list-objects-v2 --bucket "$bucket" --max-keys 1 >/dev/null 2>&1; then ok "$e: s3 ls $bucket"
    else bad "$e: $bucket 목록 조회 실패 (정책의 ListBucket 확인)"; failed=1; fi
    if aws_with "$ak" "$sk" "$region" s3api list-objects-v2 --bucket "$BACKUP_BUCKET" --prefix "$e/" --max-keys 1 >/dev/null 2>&1; then ok "$e: s3 ls $BACKUP_BUCKET/$e/"
    else bad "$e: $BACKUP_BUCKET/$e/ 조회 실패 (버킷이 없거나 정책의 prefix 조건)"; failed=1; fi
  done
  ak=""; sk=""
  # 수명주기 30일은 .env 의 좁은 키로는 못 읽는다(버킷 설정 읽기 권한이 없다). 관리자
  # 프로필이 살아 있을 때만 판정하고, 없으면 실패가 아니라 "확인 못 함"으로 둔다 —
  # 이 단계의 합격은 .env 의 키로 한 검증이 정한다.
  if ! aws --profile "$AWS_SSO_PROFILE" --no-cli-pager sts get-caller-identity >/dev/null 2>&1; then
    warn "$BACKUP_BUCKET 수명주기(30일)는 확인하지 못했습니다 — 프로필 $AWS_SSO_PROFILE 만료 (aws sso login --profile $AWS_SSO_PROFILE 뒤 다시 보면 판정합니다)"
  elif days=$(aws --profile "$AWS_SSO_PROFILE" --no-cli-pager s3api get-bucket-lifecycle-configuration \
              --bucket "$BACKUP_BUCKET" --query 'Rules[?Status==`Enabled`].Expiration.Days' --output text 2>/dev/null); then
    if printf '%s\n' "$days" | tr '\t' '\n' | grep -qx 30; then ok "$BACKUP_BUCKET 수명주기 30일 (프로필 $AWS_SSO_PROFILE 로 확인)"
    else bad "$BACKUP_BUCKET 에 30일 만료 규칙이 없습니다 (지금: ${days:-없음})"; failed=1; fi
  else
    bad "$BACKUP_BUCKET 에 수명주기 규칙이 없거나 버킷이 없습니다 (프로필 $AWS_SSO_PROFILE 로 확인)"; failed=1
  fi
  return "$failed"
}
guide_aws() {
  say "홈서버에는 인스턴스 role 이 없으므로 환경마다 IAM 사용자 하나와 access key 를 씁니다."
  say "각 사용자는 자기 영상 버킷과 $BACKUP_BUCKET 의 자기 prefix 만 봅니다 — dev·운영 데이터 경계의 실체입니다."
  printf '\n'
  step "버킷 $BACKUP_BUCKET 생성 (ap-northeast-2, 퍼블릭 액세스 차단 유지)"
  open_url "https://s3.console.aws.amazon.com/s3/bucket/create?region=ap-northeast-2"
  step "그 버킷 → Management → Lifecycle rules → Create rule: 모든 객체에 적용, 'Expire current versions of objects' 30일"
  printf '\n'
  step "IAM 사용자 acttub-home-dev 생성(콘솔 접근 없음) → Permissions → Add inline policy → JSON:"
  open_url "https://console.aws.amazon.com/iam/home#/users/create"
  print_iam_policy dev
  step "Security credentials → Create access key → 'Application running outside AWS' → 두 값을 복사"
  step "acttub-home-prod 도 같은 방법으로 — 정책의 dev 를 prod 로 바꿉니다(버킷 acttub-practice-videos-prod, prefix prod/)"
  note "ListBucket 은 빼지 마세요. 없으면 S3 가 없는 객체에 404 대신 403 을 주어 업로드 완료 API 가 500 이 됩니다(DEPLOY-VPC.md §3-3)."
  printf '\n'
  say "서버 .env 에 넣습니다($DEPLOY_USER 계정으로):"
  cmd "ssh ${DEPLOY_USER}@${SERVER_HOST}" \
      "nano $SVC_ROOT/dev/.env       # prod 는 $SVC_ROOT/prod/.env" \
      "  AWS_ACCESS_KEY_ID=AKIA..." \
      "  AWS_SECRET_ACCESS_KEY=..." \
      "  AWS_REGION=ap-northeast-2" \
      "  S3_BUCKET=acttub-practice-videos-dev      # prod 는 -prod" \
      "  BACKUP_BUCKET=$BACKUP_BUCKET"
  note "검증은 SSO 프로필이 아니라 .env 의 키로 합니다(get-caller-identity·버킷 목록). 수명주기만 프로필 $AWS_SSO_PROFILE 로 봅니다 — 만료면 aws sso login --profile $AWS_SSO_PROFILE."
}

# ── 6. .env 둘 채우기 ────────────────────────────────────────────────────
verify_env_files() {
  local failed=0 e out first owner mode missing vals project devauth n
  n=$(printf '%s\n' $REQUIRED_ENV_KEYS | wc -l | tr -d ' ')
  for e in $ENVS; do
    out=$(env_file_state "$e" $REQUIRED_ENV_KEYS $OPTIONAL_ENV_KEYS) || { deploy_ssh_failed "$e"; failed=1; continue; }
    first=$(nth_line "$out" 1)
    if [[ "$first" == MISSING ]]; then bad "$e: $SVC_ROOT/$e/.env 가 없습니다"; failed=1; continue; fi
    if [[ "$(nth_line "$out" 2)" == UNREADABLE ]]; then bad "$e: .env 를 $DEPLOY_USER 가 읽지 못합니다 (소유 $first — chown $DEPLOY_USER 후 600)"; failed=1; continue; fi
    owner=${first%% *}; mode=${first##* }
    if [[ "$owner" == "$DEPLOY_USER" && "$mode" == 600 ]]; then ok "$e: .env 소유 $owner, 권한 $mode"
    else bad "$e: .env 는 소유 $DEPLOY_USER · 권한 600 이어야 합니다 (지금: $first)"; failed=1; fi
    missing=$(printf '%s\n' "$out" | sed -n 's/^MISSING //p' | grep -xF -f <(printf '%s\n' $REQUIRED_ENV_KEYS) | tr '\n' ' ' || true)
    if [[ -n "${missing// /}" ]]; then bad "$e: 비어 있는 필수 키 — $missing"; failed=1
    else ok "$e: 필수 키 ${n}개 모두 값이 있음"; fi
    missing=$(printf '%s\n' "$out" | sed -n 's/^MISSING //p' | grep -xF -f <(printf '%s\n' $OPTIONAL_ENV_KEYS) | tr '\n' ' ' || true)
    [[ -n "${missing// /}" ]] && warn "$e: 선택 키가 비어 있음(오늘 api.env 에 있으면 옮기세요) — $missing"
    vals=$(read_env_values "$e" COMPOSE_PROJECT_NAME DEVELOPMENT_AUTH_PROVIDER) || { deploy_ssh_failed "$e"; failed=1; continue; }
    project=$(strip_quotes "$(nth_line "$vals" 1)"); devauth=$(strip_quotes "$(nth_line "$vals" 2)")
    if [[ "$project" == "acttub-$e" ]]; then ok "$e: COMPOSE_PROJECT_NAME=$project"
    else bad "$e: COMPOSE_PROJECT_NAME 은 acttub-$e 여야 합니다 (지금: '${project}')"; failed=1; fi
    case "$e:$devauth" in
      dev:1|dev:true)          ok "dev: DEVELOPMENT_AUTH_PROVIDER=$devauth (지금 dev 와 같음)" ;;
      dev:*)                   bad "dev: DEVELOPMENT_AUTH_PROVIDER=1 이 있어야 합니다 (지금: '${devauth}')"; failed=1 ;;
      prod:|prod:0|prod:false) ok "prod: DEVELOPMENT_AUTH_PROVIDER 꺼짐" ;;
      prod:*)                  bad "prod: DEVELOPMENT_AUTH_PROVIDER 가 켜져 있습니다 — 지워야 합니다"; failed=1 ;;
    esac
  done
  return "$failed"
}
guide_env_files() {
  say ".env 는 서버에만 있고 사람이 씁니다. 견본은 deploy/home/.env.example, 최종 목록은 docs/deploy/DEPLOY-HOME.md 입니다."
  cmd "COMPOSE_PROJECT_NAME=acttub-dev             # prod 는 acttub-prod" \
      "POSTGRES_PASSWORD=<openssl rand -hex 24>     # DATABASE_URL 은 적지 않는다 — compose 가 이 값으로 조립" \
      "JWT_SECRET=<지금 dev 의 값을 그대로 쓰면 기존 로그인이 유지됩니다>" \
      "ADMIN_OPS_TOKEN=…   GEMINI_API_KEY=…   OPENAI_API_KEY=…" \
      "S3_BUCKET · AWS_REGION · AWS_ACCESS_KEY_ID · AWS_SECRET_ACCESS_KEY · BACKUP_BUCKET   # 5단계" \
      "TUNNEL_TOKEN                                # 4단계" \
      "DEVELOPMENT_AUTH_PROVIDER=1                 # dev 에만. prod 에는 두지 않습니다" \
      "SENTRY_DSN=…   SENTRY_ENVIRONMENT=<지금 api.env 값 그대로>        # 선택(비면 Sentry 꺼짐)" \
      "APPLE_OAUTH_CLIENT_ID=…   GOOGLE_OAUTH_CLIENT_ID=…                # 선택(오늘 값이 있으면 옮김)"
  note "지금 dev 의 값은 dev EC2 의 /etc/acttub/api.env 에 있습니다(SSM 세션에서 sudo cat). 리소스 상한(API_MEM_LIMIT 등)은 .env.example 의 기본값·주석을 따르세요."
  printf '\n'
  cmd "ssh ${DEPLOY_USER}@${SERVER_HOST}" \
      "umask 077" \
      "nano $SVC_ROOT/dev/.env       # prod 는 $SVC_ROOT/prod/.env" \
      "chmod 600 $SVC_ROOT/dev/.env $SVC_ROOT/prod/.env"
}

# ── 7. sshd 외부 노출 — 사용자 결정 ──────────────────────────────────────
report_sshd() {
  local out cfg listen logins pw
  # sshd 는 같은 항목의 첫 값을 쓰고, Ubuntu 는 sshd_config 맨 위에서 sshd_config.d/*.conf 를
  # Include 한다. 그래서 .d 파일(이름순)을 먼저, 본문을 나중에 읽어 첫 값을 고른다.
  out=$(on_server "$ADMIN_USER" '
    for f in /etc/ssh/sshd_config.d/*.conf /etc/ssh/sshd_config; do
      [ -f "$f" ] && grep -iE "^[[:space:]]*(PasswordAuthentication|KbdInteractiveAuthentication|PermitRootLogin)[[:space:]]" "$f" | sed "s#^#${f#/etc/ssh/}: #"
    done | tr "\n" ";"; echo
    ss -tln 2>/dev/null | awk "\$4 ~ /:22\$/ {print \$4}" | tr "\n" " "; echo
    last -i -n 60 2>/dev/null | awk "NF && \$1 !~ /^(reboot|wtmp)/ && \$3 !~ /^(100\\.|192\\.168\\.|10\\.|172\\.(1[6-9]|2[0-9]|3[01])\\.|127\\.|0\\.0\\.0\\.0|::|fd|fe80)/ {print \$1, \$3, \$4, \$5, \$6, \$7}" | head -5 | tr "\n" ";"
  ') || { bad "서버에 접속하지 못했습니다: ssh ${ADMIN_USER}@${SERVER_HOST}"; return 1; }
  cfg=$(nth_line "$out" 1); listen=$(nth_line "$out" 2); logins=$(nth_line "$out" 3)
  say "sshd 설정(파일에 적힌 것만, sudo 없이 읽음): ${cfg:-없음}"
  pw=$(printf '%s' "$cfg" | tr ';' '\n' | awk 'tolower($2) == "passwordauthentication" { print tolower($3); exit }')
  if [[ "$pw" == no ]]; then ok "비밀번호 로그인 꺼짐 (첫 값 기준. 실제 적용값은 sudo sshd -T 로)"
  else warn "PasswordAuthentication 첫 값이 '${pw:-없음}' — OpenSSH 기본값은 허용입니다"; fi
  say "22번 리슨: ${listen:-없음}"
  if [[ -n "${logins// /}" ]]; then
    warn "사설망이 아닌 주소에서 온 최근 로그인(최대 5개):"
    printf '%s\n' "$logins" | tr ';' '\n' | sed '/^$/d' | while IFS= read -r l; do note "    $l"; done
    warn "→ sshd 22번이 인터넷에서 닿는다는 뜻입니다(공유기 포트포워딩 또는 DMZ)."
  else
    note "최근 60건 로그인 기록에는 사설망 밖 주소가 없습니다 — 노출이 없다는 뜻은 아닙니다. 공유기 설정을 직접 보세요."
  fi
  return 0
}
guide_sshd() {
  say "권고: 운영을 올리기 전에 아래 둘 중 하나 이상. 이 wizard 는 결정만 묻고 실행은 사람이 합니다."
  step "A. 공유기 관리 화면에서 22번 포트포워딩·DMZ 를 지웁니다. 접속은 Tailscale SSH 로만 합니다(sshd 를 거치지 않으므로 영향 없음)."
  step "B. sshd 의 비밀번호 로그인을 끕니다(키 전용). 서버에서:"
  cmd "printf 'PasswordAuthentication no\\nKbdInteractiveAuthentication no\\nPermitRootLogin prohibit-password\\n' | sudo tee /etc/ssh/sshd_config.d/01-acttub-hardening.conf" \
      "sudo sshd -t && sudo systemctl reload ssh" \
      "sudo sshd -T | grep -iE 'passwordauthentication|kbdinteractiveauthentication'"
  note "sshd 는 같은 항목의 첫 값을 쓰므로 sshd_config.d 안에서 이름이 앞서는(01-) 파일이 이깁니다. sshd -T 가 실제 적용값입니다."
  note "B 를 하기 전에 Tailscale SSH(이 wizard 가 쓰는 길)가 되는지 3단계로 확인해 두세요. 모니터·키보드 콘솔도 되돌릴 길입니다."
}

# ── 8. 최종 확인 ─────────────────────────────────────────────────────────
verify_final() {
  local failed=0 out e state
  if out=$(on_server "$DEPLOY_USER" 'docker ps -q 2>/dev/null | wc -l | tr -d " "'); then ok "ssh ${DEPLOY_USER}@${SERVER_HOST} docker ps (컨테이너 ${out}개)"
  else bad "ssh ${DEPLOY_USER}@${SERVER_HOST} docker ps 실패 (2·3단계, docker 그룹)"; failed=1; fi
  for e in $ENVS; do
    state=$(on_server "$DEPLOY_USER" "
      test -f '$SVC_ROOT/$e/compose.yml' || { echo NO_COMPOSE; exit 0; }
      test -f '$SVC_ROOT/$e/release.env' || { echo NO_RELEASE; exit 0; }
      p=\$(grep -E '^COMPOSE_PROJECT_NAME=' '$SVC_ROOT/$e/.env' 2>/dev/null | tail -n1 | cut -d= -f2-); p=\${p:-acttub-$e}
      id=\$(docker ps -q --filter label=com.docker.compose.project=\$p --filter label=com.docker.compose.service=cloudflared | head -n1)
      [ -n \"\$id\" ] || { echo NOT_RUNNING; exit 0; }
      docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' \"\$id\"
    ") || { deploy_ssh_failed "$e"; failed=1; continue; }
    case "$e:$state" in
      dev:NO_COMPOSE)  bad "dev: $SVC_ROOT/dev/compose.yml 이 아직 없습니다 — 첫 dev 배포(배포 워크플로)가 놓은 뒤 --check 로 다시"; failed=1 ;;
      dev:NO_RELEASE)  bad "dev: release.env 가 아직 없습니다(첫 배포가 씁니다) — 그 전에는 compose 가 API_IMAGE 없음으로 거부합니다"; failed=1 ;;
      prod:NO_COMPOSE|prod:NO_RELEASE) note "prod: compose·release.env 없음 — 운영을 홈서버로 옮기는 날에 다시 봅니다" ;;
      *:NOT_RUNNING)   bad "$e: cloudflared 컨테이너가 떠 있지 않습니다"; failed=1 ;;
      *:healthy|*:running) ok "$e: cloudflared $state" ;;
      *)               bad "$e: cloudflared 상태 $state"; failed=1 ;;
    esac
  done
  return "$failed"
}
guide_final() {
  say "이 맥에서 $DEPLOY_USER 계정으로 docker 가 되는지, 터널 컨테이너가 살아나는지 봅니다."
  if on_server "$DEPLOY_USER" "test -f '$SVC_ROOT/dev/compose.yml' && test -f '$SVC_ROOT/dev/release.env'" 2>/dev/null; then
    # compose.yml 머리말대로 --env-file 둘을 넘겨야 release.env 의 API_IMAGE 가 보인다.
    cmd "ssh ${DEPLOY_USER}@${SERVER_HOST}" \
        "cd $SVC_ROOT/dev && docker compose --env-file .env --env-file release.env up -d cloudflared"
    note "healthy 가 되면 Cloudflare 대시보드의 터널 상태도 Healthy 로 바뀌고, ${DEV_TEMP_HOST} 가 530 대신 web 의 응답을 냅니다(web 이 아직 없으면 502)."
  else
    warn "compose.yml·release.env 가 아직 서버에 없습니다 — 첫 dev 배포(배포 워크플로)가 놓습니다. 지금은 s 로 건너뛰고, 그 뒤에 다시 실행하세요:"
    cmd "deploy/home/prepare-server.sh --check"
  fi
}

# ── 단계표 — 대화형·--check 가 같은 표를 쓴다 ───────────────────────────────
STAGE_TITLES=(
  "1. 재부팅(커널)·docker 패키지 업그레이드"
  "2. ${DEPLOY_USER} 계정(docker 그룹, sudo 없음)·${SVC_ROOT}/{dev,prod}"
  "3. Tailscale — 규칙 → 태그 → 사람 SSH 재확인 → OAuth → GitHub secrets"
  "4. Cloudflare Tunnel acttub-dev·acttub-prod, ${DEV_TEMP_HOST} → web:3000"
  "5. AWS — IAM 사용자 acttub-home-{dev,prod}, 버킷 ${BACKUP_BUCKET}(30일)"
  "6. .env 둘 채우기 (권한 600·필수 키)"
  "7. sshd 외부 노출 (사용자 결정)"
  "8. 최종 확인 — ${DEPLOY_USER} 로 docker ps, cloudflared healthy"
)
STAGE_VERIFY=(verify_reboot_docker verify_deploy_account verify_tailscale verify_tunnel verify_aws verify_env_files report_sshd verify_final)
STAGE_GUIDE=(guide_reboot_docker guide_deploy_account guide_tailscale guide_tunnel guide_aws guide_env_files guide_sshd guide_final)
SSHD_STAGE_INDEX=6   # 7단계는 합격·불합격이 아니라 사용자 결정이라 따로 돈다

# ── 진행 방식 ─────────────────────────────────────────────────────────────
# gate VERIFY GUIDE — 사람이 마쳤다고 할 때마다 다시 검증한다.
gate() {
  local verify="$1" guide="$2" reply
  while :; do
    printf '\n  %s마쳤으면 Enter(다시 확인) · g = 안내 다시 보기 · s = 건너뛰기%s ' "$DIM" "$RESET"
    # 입력이 끝나면(EOF) 빈 Enter 로 읽혀 영원히 재검증한다 — 그 대신 중단한다.
    read -r reply || { printf '\n'; warn "입력이 끝나 중단합니다 — 다시 실행하면 이 단계부터 검증합니다"; exit 130; }
    case "$reply" in
      [Ss]*) SKIPPED+=("$CURRENT_STAGE"); warn "건너뜁니다 — 다음 실행 때 이 단계부터 다시 검증합니다"; return 1 ;;
      [Gg]*) printf '\n'; "$guide"; continue ;;
    esac
    printf '\n'
    if "$verify"; then printf '\n'; ok "확인됐습니다"; return 0; fi
    warn "아직입니다 — 위 ✗ 항목을 처리한 뒤 다시 확인하세요"
  done
}

# run_stage "제목" VERIFY GUIDE — 먼저 검증하고, 되어 있으면 안내 없이 지나간다(재개).
run_stage() {
  local title="$1" verify="$2" guide="$3"
  CURRENT_STAGE="$title"
  stage "$title"; printf '\n'
  if "$verify"; then
    printf '\n'; ok "이미 되어 있습니다 — 검증만 하고 넘어갑니다"
  else
    printf '\n'; "$guide"
    gate "$verify" "$guide" || true
  fi
  pause "Enter 로 다음 단계"
}

# run_stage_sshd "제목" — 관찰을 보여 주고 결정만 묻는다. 실행은 사람이 한다.
run_stage_sshd() {
  CURRENT_STAGE="$1"
  stage "$CURRENT_STAGE"; printf '\n'
  report_sshd || true
  printf '\n'; guide_sshd; printf '\n'
  if confirm "처리했나요? (y = 처리함, 다시 확인 · n = 결정 보류로 남김)"; then
    printf '\n'; report_sshd || true
  else
    SKIPPED+=("$CURRENT_STAGE — 포트포워딩·비밀번호 로그인 처리 여부를 정하지 않음")
  fi
  pause "Enter 로 다음 단계"
}

require_tools() {
  local t missing=""
  for t in ssh jq curl aws gh; do command -v "$t" >/dev/null 2>&1 || missing="$missing $t"; done
  if [[ -n "$missing" ]]; then
    warn "이 맥에 없는 도구:$missing — 해당 검증(aws: 5단계, gh: 3단계)은 실패로 나옵니다"
  fi
}

interactive() {
  local i
  require_tools
  banner "Acttub 홈서버 준비 — 서버·계정·터널·IAM (${SERVER_HOST})"
  for i in 0 1 2 3 4 5 6 7; do
    if [[ "$i" -eq "$SSHD_STAGE_INDEX" ]]; then run_stage_sshd "${STAGE_TITLES[$i]}"
    else run_stage "${STAGE_TITLES[$i]}" "${STAGE_VERIFY[$i]}" "${STAGE_GUIDE[$i]}"; fi
  done
  finish
}

# --check: 묻지 않고 8단계를 검증만 한다. 남은 단계가 있으면 exit 1.
check_mode() {
  local i status pending="" decided=""
  require_tools
  printf '\n%s%s홈서버 준비 상태 — %s (검증만, 바꾸지 않음)%s\n' "$BOLD" "$BLUE" "$SERVER_HOST" "$RESET"
  note "Tailscale 재확인 링크가 뜨면 브라우저에서 승인해야 이어집니다."
  for i in 0 1 2 3 4 5 6 7; do
    printf '\n%s▸ %s%s\n' "$BOLD" "${STAGE_TITLES[$i]}" "$RESET"
    if [[ "$i" -eq "$SSHD_STAGE_INDEX" ]]; then
      report_sshd || true
      note "→ 결정 사항(사용자). 대화형 실행에서 처리 여부를 답합니다."
      decided="$decided"$'\n'"  • ${STAGE_TITLES[$i]}"
      continue
    fi
    if "${STAGE_VERIFY[$i]}"; then status="${GREEN}완료${RESET}"
    else status="${RED}아직${RESET}"; pending="$pending"$'\n'"  • ${STAGE_TITLES[$i]}"; fi
    printf '  → %s\n' "$status"
  done
  printf '\n%s%s요약%s\n' "$BOLD" "$BLUE" "$RESET"
  if [[ -z "$pending" ]]; then
    ok "검증 가능한 단계는 모두 되어 있습니다"
  else
    printf '  %s아직:%s%s\n' "$YELLOW" "$RESET" "$pending"
  fi
  [[ -n "$decided" ]] && printf '  %s결정 사항:%s%s\n' "$DIM" "$RESET" "$decided"
  printf '\n'
  [[ -z "$pending" ]]
}

usage() {
  printf 'usage: %s [--check]\n' "${0##*/}"
  printf '  (없음)    대화형 — 8단계를 순서대로 안내하고 검증합니다\n'
  printf '  --check   검증만 — 묻지 않고 상태를 보고합니다(남은 단계가 있으면 exit 1)\n'
}

trap 'printf "\n  중단했습니다. 다시 실행하면 된 단계는 검증만 하고 지나갑니다.\n"; exit 130' INT

case "${1:-}" in
  --check|-c) check_mode ;;
  -h|--help)  usage ;;
  "")         interactive ;;
  *)          usage >&2; exit 2 ;;
esac
