package com.acttub.actingapi.consent;
import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*; import com.acttub.actingapi.domain.ConsentType; import com.fasterxml.jackson.annotation.JsonIgnoreProperties; import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper; import org.postgresql.util.PSQLException; import org.slf4j.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.boot.*; import org.springframework.core.io.*; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Component;
@Component public class ConsentDocumentPublisher implements ApplicationRunner {
    private static final Logger log=LoggerFactory.getLogger(ConsentDocumentPublisher.class);private final JdbcTemplate jdbc;private final ObjectMapper mapper;private final ResourceLoader resources;private final String configuredDir;
    public ConsentDocumentPublisher(JdbcTemplate jdbc,ObjectMapper mapper,ResourceLoader resources,@Value("${CONSENT_DOCS_DIR:}")String configuredDir){this.jdbc=jdbc;this.mapper=mapper;this.resources=resources;this.configuredDir=configuredDir;}
    @JsonIgnoreProperties(ignoreUnknown=false) record Entry(String file,String type,String version,String title,boolean required){} private record Validated(Entry entry,ConsentType type,String body){}
    @Override public void run(ApplicationArguments args){try{publish();}catch(Exception e){log.error("Consent document startup seed failed",e);}}
    public int publish()throws Exception{Resource manifest=resource("manifest.json");if(!manifest.exists()){log.warn("Consent documents manifest is missing: {}",manifest);return 0;}List<Entry> entries=mapper.readValue(manifest.getInputStream(),new TypeReference<>(){});List<Validated> all=new ArrayList<>();for(Entry e:entries){ConsentType type=Arrays.stream(ConsentType.values()).filter(v->v.dbValue().equals(e.type())).findFirst().orElseThrow(()->new IllegalArgumentException("invalid consent type: "+e.type()));if(e.file()==null||e.file().isBlank()||e.version()==null||e.version().isBlank()||e.title()==null||e.title().isBlank())throw new IllegalArgumentException("invalid consent manifest entry");Resource body=resource(e.file());if(!body.exists())throw new java.io.FileNotFoundException(e.file());all.add(new Validated(e,type,new String(body.getInputStream().readAllBytes(),StandardCharsets.UTF_8)));}
        int published=0;for(Validated value:all){Entry e=value.entry();List<Map<String,Object>> existing=jdbc.queryForList("SELECT title,body,required FROM consent_documents WHERE type=?::consent_type_t AND version=?",value.type().dbValue(),e.version());if(!existing.isEmpty()){Map<String,Object> row=existing.getFirst();List<String> mismatch=new ArrayList<>();if(!Objects.equals(row.get("title"),e.title()))mismatch.add("title");if(!Objects.equals(row.get("body"),value.body()))mismatch.add("body");if(!Objects.equals(row.get("required"),e.required()))mismatch.add("required");if(!mismatch.isEmpty())log.warn("Consent document {}:{} differs in fields: {}; publish a new version",value.type().dbValue(),e.version(),mismatch);continue;}try{jdbc.update("INSERT INTO consent_documents(id,type,version,title,body,required) VALUES (?,?::consent_type_t,?,?,?,?)",UUID.randomUUID(),value.type().dbValue(),e.version(),e.title(),value.body(),e.required());published++;}catch(DataIntegrityViolationException ex){if(!isUniqueRace(ex))throw ex;}}
        log.info("Published {} consent documents during startup",published);return published;}
    private Resource resource(String name){if(configuredDir!=null&&!configuredDir.isBlank())return new FileSystemResource(Path.of(configuredDir).resolve(name));return resources.getResource("classpath:consent-docs/"+name);}
    static boolean isUniqueRace(Throwable value){for(Throwable t=value;t!=null;t=t.getCause())if(t instanceof PSQLException p&&p.getServerErrorMessage()!=null&&"23505".equals(p.getSQLState())&&"uq_consent_documents_type_version".equals(p.getServerErrorMessage().getConstraint()))return true;return false;}
}
