package com.acttub.actingapi.oidc;
import static org.assertj.core.api.Assertions.*; import java.time.Instant; import java.util.*; import org.junit.jupiter.api.Test; import org.springframework.security.oauth2.core.OAuth2Error; import org.springframework.security.oauth2.jwt.*;
class ProviderVerifierTest {private static Jwt jwt(Map<String,Object> claims){return Jwt.withTokenValue("t").header("alg","RS256").claims(c->c.putAll(claims)).issuedAt(Instant.now()).expiresAt(Instant.now().plusSeconds(60)).build();}
    @Test void googleNormalizesClaimsAndConfiguration(){Map<String,Object> claims=new HashMap<>(Map.of("sub","g","email","","email_verified","TrUe","iss","https://accounts.google.com","aud",List.of("client")));GoogleProviderVerifier verifier=new GoogleProviderVerifier("client",token->jwt(claims));assertThat(verifier.verify("t")).isEqualTo(new ProviderIdentity("g",null,true));assertThatThrownBy(()->new GoogleProviderVerifier("",token->jwt(claims)).verify("t")).isInstanceOf(ProviderConfigurationError.class);}
    @Test void appleAcceptsAnyConfiguredAudienceAndBoolOrStringVerified(){Map<String,Object> claims=new HashMap<>(Map.of("sub","a","email","a@example.test","email_verified",true,"iss",AppleProviderVerifier.ISSUER,"aud",List.of("service")));AppleProviderVerifier verifier=new AppleProviderVerifier("bundle, service",token->jwt(claims));assertThat(verifier.verify("t").emailVerified()).isTrue();claims.put("email_verified","TRUE");assertThat(verifier.verify("t").emailVerified()).isTrue();claims.remove("sub");assertThatThrownBy(()->verifier.verify("t")).isInstanceOf(InvalidIdentityToken.class);assertThatThrownBy(()->new AppleProviderVerifier("",null).verify("t")).isInstanceOf(ProviderConfigurationError.class);}
    @Test void decoderFailuresCoverWrongIssuerAudienceAndExpired(){for(String provider:List.of("google","apple")){JwtDecoder failing=token->{throw new JwtValidationException("invalid",List.of(new OAuth2Error("invalid_token")));};ProviderVerifier verifier=provider.equals("google")?new GoogleProviderVerifier("client",failing):new AppleProviderVerifier("client",failing);assertThatThrownBy(()->verifier.verify("wrong issuer/audience/expired")).isInstanceOf(InvalidIdentityToken.class);}}
    @Test void googleSevenVectorValidatorDiscriminatesIssuerAudienceAndExpiry(){var valid=jwt(Map.of("iss","https://accounts.google.com","aud",List.of("client"),"sub","g","email","g@example.test","email_verified",true));assertThat(GoogleProviderVerifier.validator("client").validate(valid).hasErrors()).isFalse();assertThat(GoogleProviderVerifier.validator("client").validate(jwt(Map.of("iss","wrong","aud",List.of("client"),"sub","g"))).hasErrors()).isTrue();assertThat(GoogleProviderVerifier.validator("other").validate(valid).hasErrors()).isTrue();Jwt expired=Jwt.withTokenValue("t").header("alg","RS256").claim("iss","https://accounts.google.com").claim("aud",List.of("client")).claim("sub","g").issuedAt(Instant.now().minusSeconds(300)).expiresAt(Instant.now().minusSeconds(120)).build();assertThat(GoogleProviderVerifier.validator("client").validate(expired).hasErrors()).isTrue();}
    @Test void appleSevenVectorValidatorDiscriminatesIssuerAudienceAndExpiry(){var valid=jwt(Map.of("iss",AppleProviderVerifier.ISSUER,"aud",List.of("service"),"sub","a","email","a@example.test","email_verified","true"));assertThat(AppleProviderVerifier.validator("bundle,service").validate(valid).hasErrors()).isFalse();assertThat(AppleProviderVerifier.validator("bundle,service").validate(jwt(Map.of("iss","wrong","aud",List.of("service"),"sub","a"))).hasErrors()).isTrue();assertThat(AppleProviderVerifier.validator("bundle").validate(valid).hasErrors()).isTrue();Jwt expired=Jwt.withTokenValue("t").header("alg","RS256").claim("iss",AppleProviderVerifier.ISSUER).claim("aud",List.of("service")).claim("sub","a").issuedAt(Instant.now().minusSeconds(300)).expiresAt(Instant.now().minusSeconds(120)).build();assertThat(AppleProviderVerifier.validator("bundle,service").validate(expired).hasErrors()).isTrue();}
}
