package com.acttub.actingapi.auth;
import java.time.*; import java.util.*; import jakarta.servlet.http.HttpServletRequest; import jakarta.validation.Valid; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.http.*; import org.springframework.web.bind.annotation.*; import com.acttub.actingapi.domain.UserStatus; import com.acttub.actingapi.web.ApiException; import io.swagger.v3.oas.annotations.*; import io.swagger.v3.oas.annotations.media.*; import io.swagger.v3.oas.annotations.responses.*; import io.swagger.v3.oas.annotations.security.SecurityRequirement; import static com.acttub.actingapi.auth.AuthDtos.*;
@RestController @RequestMapping("/v2/auth") public class AuthController {
    private final ProviderRegistry providers;private final AuthStore store;private final JwtService jwt;private final CurrentUserService users;private final FixedWindowRateLimiter limiter;private final Clock clock;
    public AuthController(ProviderRegistry providers,AuthStore store,JwtService jwt,CurrentUserService users,FixedWindowRateLimiter limiter,Clock clock){this.providers=providers;this.store=store;this.jwt=jwt;this.users=users;this.limiter=limiter;this.clock=clock;}
    @Operation(summary="Login",operationId="login_v2_auth_login_post",tags="v2-auth") @ApiResponses({@ApiResponse(responseCode="200",description="Successful Response",content=@Content(schema=@Schema(implementation=TokenPairResponse.class))),@ApiResponse(responseCode="422",description="Validation Error",content=@Content(schema=@Schema(implementation=HTTPValidationError.class)))})
    @PostMapping("/login") TokenPairResponse login(@Valid @RequestBody LoginRequest body,HttpServletRequest request){ipLimit(request);String provider=body.provider().strip().toLowerCase(Locale.ROOT);ProviderIdentity identity;try{identity=providers.verify(provider,body.idToken());}catch(UnsupportedProviderError e){throw new ApiException(400,"unsupported_provider");}catch(ProviderConfigurationError e){throw new ApiException(503,"provider_not_configured");}catch(InvalidIdentityToken e){throw new ApiException(401,"invalid_provider_token");}
        AuthStore.User user=store.getUserByIdentity(provider,identity.providerUid());if(user==null){String email=normalize(identity.email());AuthStore.User existing=email==null?null:store.getUserByEmail(email);try{if(existing!=null){if(!identity.emailVerified())throw new ApiException(409,"account_exists_with_different_provider");store.linkIdentity(existing.id(),provider,identity.providerUid());user=existing;}else user=store.createUserWithIdentity(provider,identity.providerUid(),identity.emailVerified()?email:null,body.signupAttribution());}catch(DataIntegrityViolationException|IdentityAlreadyLinkedError race){user=store.getUserByIdentity(provider,identity.providerUid());if(user==null)throw race;}}checkUser(user);userLimit(user);return pair(user,request.getHeader("user-agent"));}
    @Operation(summary="Refresh",operationId="refresh_v2_auth_refresh_post",tags="v2-auth") @ApiResponses({@ApiResponse(responseCode="200",description="Successful Response",content=@Content(schema=@Schema(implementation=RefreshTokenResponse.class))),@ApiResponse(responseCode="422",description="Validation Error",content=@Content(schema=@Schema(implementation=HTTPValidationError.class)))})
    @PostMapping("/refresh") RefreshTokenResponse refresh(@Valid @RequestBody RefreshRequest body,HttpServletRequest request){ipLimit(request);Instant now=clock.instant();JwtService.TokenClaims claims;try{claims=jwt.decode(body.refreshToken(),"refresh",now);}catch(JwtService.TokenValidationException e){throw new ApiException(401,"invalid_refresh_token");}String oldHash=JwtService.hashToken(body.refreshToken());AuthStore.StoredRefresh old=store.getRefresh(oldHash);if(old==null||!old.userId().equals(claims.userId()))throw new ApiException(401,"invalid_refresh_token");AuthStore.User user=store.getUser(claims.userId());if(user==null)throw new ApiException(401,"invalid_refresh_token");checkUser(user);userLimit(user);var access=jwt.issue(user.id(),"access",JwtService.ACCESS_TTL_SECONDS,now);var replacement=jwt.issue(user.id(),"refresh",JwtService.REFRESH_TTL_SECONDS,now);var rotation=store.rotate(oldHash,JwtService.hashToken(replacement.value()),replacement.expiresAt(),request.getHeader("user-agent"),now);if(rotation.reused()||rotation.id()==null)throw new ApiException(401,"invalid_refresh_token");return new RefreshTokenResponse(access.value(),replacement.value(),"bearer",JwtService.ACCESS_TTL_SECONDS);}
    @Operation(summary="Logout",operationId="logout_v2_auth_logout_post",tags="v2-auth",security=@SecurityRequirement(name="HTTPBearer")) @ApiResponses({@ApiResponse(responseCode="204",description="No Content"),@ApiResponse(responseCode="422",description="Validation Error",content=@Content(schema=@Schema(implementation=HTTPValidationError.class)))})
    @PostMapping("/logout") ResponseEntity<Void> logout(@Valid @RequestBody LogoutRequest body,HttpServletRequest request){AuthStore.User user=users.require(request);userLimit(user);try{var claims=jwt.decodeRefreshToken(body.refreshToken());String hash=JwtService.hashToken(body.refreshToken());var stored=store.getRefresh(hash);if(!claims.userId().equals(user.id())||stored==null||!stored.userId().equals(user.id())||!store.revoke(hash,clock.instant()))throw new ApiException(401,"invalid_refresh_token");return ResponseEntity.noContent().build();}catch(JwtService.TokenValidationException e){throw new ApiException(401,"invalid_refresh_token");}}
    private TokenPairResponse pair(AuthStore.User user,String device){var access=jwt.issueAccessToken(user.id());var refresh=jwt.issueRefreshToken(user.id());store.issueRefresh(user.id(),JwtService.hashToken(refresh.value()),refresh.expiresAt(),device,clock.instant());return new TokenPairResponse(access.value(),refresh.value(),"bearer",JwtService.ACCESS_TTL_SECONDS,new AuthUser(user.id(),user.email(),user.status().dbValue()),store.pendingConsents(user.id()).stream().map(c->new ConsentDocument(c.id(),c.type().dbValue(),c.version(),c.title(),c.body(),c.required(),c.publishedAt())).toList());}
    private void ipLimit(HttpServletRequest r){String host=r.getRemoteAddr()==null?"unknown":r.getRemoteAddr();if(!limiter.allow("auth-ip:"+host,60))throw new ApiException(429,"rate limit exceeded");} private void userLimit(AuthStore.User u){if(!limiter.allow(u.id().toString(),60))throw new ApiException(429,"rate limit exceeded");}// 로그인·refresh 둘 다 이 검사를 지난다. **DEACTIVATED 를 빠뜨리면 탈퇴 계정이 다시
// 로그인된다** — CurrentUserService(토큰 경로)에는 있었는데 여기만 없었다(SOMA-306 흡수 누락).
private static void checkUser(AuthStore.User u){if(u.status()==UserStatus.SUSPENDED)throw new ApiException(403,"account_suspended");if(u.status()==UserStatus.DEACTIVATED)throw new ApiException(403,"account_deactivated");}private static String normalize(String email){if(email==null)return null;String v=email.strip().toLowerCase(Locale.ROOT);return v.isEmpty()?null:v;}
}
