package com.acttub.actingapi.auth;
import java.sql.ResultSet; import java.sql.SQLException; import java.time.*; import java.util.*; import com.acttub.actingapi.schema.*; import com.acttub.actingapi.security.AuthenticatedUser; import com.acttub.actingapi.security.AuthenticatedUsers; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import org.springframework.transaction.support.TransactionTemplate;
/**
 * 사용자를 소유한 쪽이 배관의 포트를 <b>직접</b> 구현한다 — 위임만 하는 어댑터를 끼우지
 * 않는다 (ADR-017, SOMA-397 6단계의 {@code SyncOperationService} 와 같은 형태).
 */
@Repository public class AuthStore implements AuthenticatedUsers {
    private final JdbcTemplate jdbc;private final TransactionTemplate tx;public AuthStore(JdbcTemplate jdbc,TransactionTemplate tx){this.jdbc=jdbc;this.tx=tx;}
    public record StoredRefresh(UUID id,UUID userId,UUID replacedById,Instant expiresAt,Instant revokedAt,String deviceInfo){} public record Rotation(UUID id,boolean reused){} public record Consent(UUID id,ConsentType type,String version,String title,String body,boolean required,Instant publishedAt){}
    @Override public AuthenticatedUser find(UUID id){return one("SELECT id,email,status::text FROM users WHERE id=?",id);}
    public AuthenticatedUser findByEmail(String email){return one("SELECT id,email,status::text FROM users WHERE lower(email)=lower(?)",email);}
    public AuthenticatedUser findByIdentity(String provider,String uid){return one("SELECT u.id,u.email,u.status::text FROM users u JOIN user_identities i ON i.user_id=u.id WHERE i.provider=?::identity_provider_t AND i.provider_uid=?",provider,uid);}
    private AuthenticatedUser one(String sql,Object...args){List<AuthenticatedUser> values=jdbc.query(sql,(rs,n)->new AuthenticatedUser(rs.getObject(1,UUID.class),rs.getString(2),UserStatus.valueOf(rs.getString(3).toUpperCase(Locale.ROOT))),args);return values.isEmpty()?null:values.getFirst();}
    // 유입 출처는 **가입할 때만** 남긴다. 이미 있는 계정에 다시 붙이면 마지막 로그인
    // 경로가 첫 유입을 덮어써서 집계가 뒤집힌다(원본도 create 경로에만 준다).
    public AuthenticatedUser createUserWithIdentity(String provider,String uid,String email,SignupAttribution attribution){return tx.execute(s->{UUID id=UUID.randomUUID();jdbc.update("INSERT INTO users(id,email,status,signup_utm_source,signup_utm_medium,signup_utm_campaign,signup_utm_id,signup_utm_content,signup_utm_term,signup_referrer_host,signup_landing_path,signup_first_seen_at) VALUES (?,?,'active'::user_status_t,?,?,?,?,?,?,?,?,?)",id,email,attribution==null?null:attribution.utmSource(),attribution==null?null:attribution.utmMedium(),attribution==null?null:attribution.utmCampaign(),attribution==null?null:attribution.utmId(),attribution==null?null:attribution.utmContent(),attribution==null?null:attribution.utmTerm(),attribution==null?null:attribution.referrerHost(),attribution==null?null:attribution.landingPath(),attribution==null||attribution.firstSeenAt()==null?null:attribution.firstSeenAt().atOffset(ZoneOffset.UTC));jdbc.update("INSERT INTO user_identities(id,user_id,provider,provider_uid) VALUES (?,?,?::identity_provider_t,?)",UUID.randomUUID(),id,provider,uid);return find(id);});}
    public void linkIdentity(UUID user,String provider,String uid){int inserted=jdbc.update("INSERT INTO user_identities(id,user_id,provider,provider_uid) VALUES (?,?,?::identity_provider_t,?) ON CONFLICT(provider,provider_uid) DO NOTHING",UUID.randomUUID(),user,provider,uid);if(inserted==0){List<UUID> owners=jdbc.query("SELECT user_id FROM user_identities WHERE provider=?::identity_provider_t AND provider_uid=?",(rs,n)->rs.getObject(1,UUID.class),provider,uid);if(owners.isEmpty()||!owners.getFirst().equals(user))throw new IdentityAlreadyLinkedError("identity is already linked to another user");}}
    public void issueRefresh(UUID user,String hash,Instant expires,String device,Instant issued){validateHash(hash);jdbc.update("INSERT INTO refresh_tokens(id,user_id,token_hash,device_info,issued_at,expires_at) VALUES (?,?,?,?,?,?)",UUID.randomUUID(),user,hash,device,issued.atOffset(ZoneOffset.UTC),expires.atOffset(ZoneOffset.UTC));}
    public StoredRefresh getRefresh(String hash){validateHash(hash);List<StoredRefresh> rows=jdbc.query("SELECT id,user_id,replaced_by_id,expires_at,revoked_at,device_info FROM refresh_tokens WHERE token_hash=?",AuthStore::refresh,hash);return rows.isEmpty()?null:rows.getFirst();}
    public Rotation rotate(String oldHash,String newHash,Instant expires,String device,Instant now){validateHash(oldHash);validateHash(newHash);return tx.execute(s->{List<StoredRefresh> rows=jdbc.query("SELECT id,user_id,replaced_by_id,expires_at,revoked_at,device_info FROM refresh_tokens WHERE token_hash=? FOR UPDATE",AuthStore::refresh,oldHash);if(rows.isEmpty())return new Rotation(null,false);StoredRefresh old=rows.getFirst();if(old.replacedById()!=null){jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL",now.atOffset(ZoneOffset.UTC),old.userId());return new Rotation(null,true);}if(old.revokedAt()!=null||!old.expiresAt().isAfter(now)){if(old.revokedAt()==null)jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE id=?",now.atOffset(ZoneOffset.UTC),old.id());return new Rotation(null,false);}UUID replacement=UUID.randomUUID();jdbc.update("INSERT INTO refresh_tokens(id,user_id,token_hash,device_info,issued_at,expires_at) VALUES (?,?,?,?,?,?)",replacement,old.userId(),newHash,device!=null?device:old.deviceInfo(),now.atOffset(ZoneOffset.UTC),expires.atOffset(ZoneOffset.UTC));jdbc.update("UPDATE refresh_tokens SET replaced_by_id=?,revoked_at=? WHERE id=?",replacement,now.atOffset(ZoneOffset.UTC),old.id());return new Rotation(replacement,false);});}
    public boolean revoke(String hash,Instant now){validateHash(hash);return jdbc.update("UPDATE refresh_tokens SET revoked_at=? WHERE token_hash=? AND revoked_at IS NULL",now.atOffset(ZoneOffset.UTC),hash)>0;}
    public List<Consent> pendingConsents(UUID user){return jdbc.query(""" 
        WITH latest AS (SELECT DISTINCT ON(type) * FROM consent_documents ORDER BY type,published_at DESC,id DESC)
        SELECT d.id,d.type::text,d.version,d.title,d.body,d.required,d.published_at
        FROM latest d WHERE d.required AND NOT EXISTS(
          SELECT 1 FROM user_consents c WHERE c.user_id=? AND c.document_id=d.id AND c.action='granted'::consent_action_t
          AND c.id=(SELECT c2.id FROM user_consents c2 WHERE c2.user_id=c.user_id AND c2.document_id=c.document_id ORDER BY c2.occurred_at DESC,c2.id DESC LIMIT 1))
        ORDER BY d.published_at,d.id
        """,(rs,n)->new Consent(rs.getObject(1,UUID.class),ConsentType.valueOf(rs.getString(2).toUpperCase(Locale.ROOT)),rs.getString(3),rs.getString(4),rs.getString(5),rs.getBoolean(6),rs.getObject(7,java.time.OffsetDateTime.class).toInstant()),user);}
    @Override public boolean hasPendingConsents(UUID user){return !pendingConsents(user).isEmpty();}
    private static StoredRefresh refresh(ResultSet rs,int n)throws SQLException{return new StoredRefresh(rs.getObject(1,UUID.class),rs.getObject(2,UUID.class),rs.getObject(3,UUID.class),rs.getObject(4,java.time.OffsetDateTime.class).toInstant(),rs.getObject(5,java.time.OffsetDateTime.class)==null?null:rs.getObject(5,java.time.OffsetDateTime.class).toInstant(),rs.getString(6));}
    private static void validateHash(String value){if(value==null||!value.matches("[0-9a-f]{64}"))throw new IllegalArgumentException("expected SHA-256 hex");}
}
