-- Additive AI pipeline v1 data plane. Legacy rows remain valid and are never backfilled into AI consent.
create or replace function public.current_acttub_ai_processing_consent_version() returns text language sql immutable as $$ select 'ai-processing.v1'::text $$;

alter table public.profiles
  add column if not exists required_consent_version text,
  add column if not exists required_consent_at timestamptz,
  add column if not exists ai_processing_consent_version text,
  add column if not exists ai_processing_consent_at timestamptz,
  add column if not exists internal_review_consent boolean not null default false,
  add column if not exists internal_review_consent_updated_at timestamptz;

alter table public.profiles drop constraint if exists active_profile_requires_current_consent;
alter table public.profiles add constraint active_profile_requires_current_consent check (
  status <> 'active' or (required_consent_version is not null and required_consent_at is not null
    and ai_processing_consent_version is not null and ai_processing_consent_at is not null)
) not valid;
create or replace function public.is_active_acttub_profile(profile_user_id uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists(select 1 from public.profiles p where p.id=profile_user_id and p.status='active'
    and p.required_consent_version is not null and p.required_consent_at is not null
    and p.ai_processing_consent_version is not null and p.ai_processing_consent_at is not null)
$$;

alter table public.upload_intents
  add column if not exists required_consent_version_snapshot text,
  add column if not exists ai_processing_consent_version_snapshot text,
  add column if not exists adult_confirmed_at timestamptz,
  add column if not exists all_participants_confirmed_at timestamptz,
  add column if not exists authoritative_duration_ms integer check(authoritative_duration_ms is null or authoritative_duration_ms between 1 and 300000),
  add column if not exists media_metadata_version text check(media_metadata_version is null or media_metadata_version='iso-bmff-duration.v1'),
  add column if not exists ai_eligible_at timestamptz;

alter table public.practice_sessions
  add column if not exists pipeline_version text check(pipeline_version is null or pipeline_version='ai-pipeline.v1'),
  add column if not exists required_consent_version_snapshot text,
  add column if not exists ai_processing_consent_version_snapshot text,
  add column if not exists adult_confirmed_at timestamptz,
  add column if not exists all_participants_confirmed_at timestamptz,
  add column if not exists interview_status text check(interview_status is null or interview_status in ('active','paused','completed','completed_without_report')),
  add column if not exists completion_reason text check(completion_reason is null or completion_reason in ('interview_complete_report_ready','manual_stop_report_ready','manual_stop_paused','hard_limit_report_ready','insufficient_confirmed_evidence','insufficient_interview_evidence')),
  add column if not exists substantive_answer_count integer check(substantive_answer_count is null or substantive_answer_count between 0 and 10),
  add column if not exists report_evidence_observation_ids uuid[] not null default '{}',
  add column if not exists report_evidence_answer_turn_ids uuid[] not null default '{}',
  add column if not exists deletion_status text not null default 'active' check(deletion_status in ('active','deleting','delete_failed')),
  add column if not exists delete_request_id uuid,
  add column if not exists delete_error_code text,
  add column if not exists delete_started_at timestamptz,
  add column if not exists delete_updated_at timestamptz,
  add constraint pipeline_consent_snapshots check(pipeline_version is null or
    (required_consent_version_snapshot is not null and ai_processing_consent_version_snapshot is not null and adult_confirmed_at is not null and all_participants_confirmed_at is not null)),
  add constraint deletion_request_required check(deletion_status='active' or delete_request_id is not null);

alter table public.practice_takes add column if not exists media_metadata_version text check(media_metadata_version is null or media_metadata_version='iso-bmff-duration.v1');
alter table public.practice_takes add constraint practice_takes_id_session_user_unique unique(id,session_id,user_id);
alter table public.observations add constraint observations_id_session_user_unique unique(id,session_id,user_id);
alter table public.practice_takes add constraint pipeline_take_duration check(duration_ms is null or duration_ms between 1 and 300000) not valid;
alter table public.observations alter column confidence drop not null;
alter table public.observations
  add column if not exists candidate_id uuid,
  add column if not exists priority integer check(priority is null or priority>0),
  add column if not exists dimension text,
  add column if not exists severity text check(severity is null or severity in ('high','mid','low')),
  add column if not exists source_run_id uuid,
  add constraint pipeline_rejected_unsure_are_blocked check(confirmation_state not in ('rejected','unsure') or blocked_for_questioning);

create table public.ai_runs (
 id uuid primary key, session_id uuid not null, user_id uuid not null, stage text not null check(stage in ('summary','agent','report','delete')),
 status text not null check(status in ('pending','running','completed','failed')), idempotency_key text not null, attempt integer not null default 0 check(attempt>=0),
 max_attempts integer not null check(max_attempts between 1 and 5), request_schema_version text, response_schema_version text, model text, prompt_version text,
 safe_error_code text, retryable boolean not null default false, started_at timestamptz, completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 unique(session_id,stage,idempotency_key), unique(id,session_id,user_id), foreign key(session_id,user_id) references public.practice_sessions(id,user_id) on delete cascade,
 check(status<>'running' or started_at is not null), check(status not in ('completed','failed') or completed_at is not null),
 check(status<>'completed' or safe_error_code is null), check(status<>'failed' or safe_error_code is not null)
);
create table public.ai_session_summaries (
 session_id uuid primary key, user_id uuid not null, take_id uuid not null, schema_version text not null check(schema_version='scene-summary.v1'),
 subtext_status text not null check(subtext_status in ('provided','not_provided')), normalized_summary jsonb not null, source_run_id uuid not null unique, created_at timestamptz not null default now(),
 unique(session_id,user_id), foreign key(session_id,user_id) references public.practice_sessions(id,user_id) on delete cascade,
 foreign key(take_id,session_id,user_id) references public.practice_takes(id,session_id,user_id) on delete cascade,
 foreign key(source_run_id,session_id,user_id) references public.ai_runs(id,session_id,user_id) on delete cascade
);
create table public.interview_turns (
 id uuid primary key, session_id uuid not null, user_id uuid not null, sequence integer not null check(sequence>=0), role text not null check(role in ('agent','actor')),
 kind text not null check(kind in ('question','closing','answer','unknown','observation_confirmation','actor_correction','optional_note')), content text not null check(length(trim(content))>0), question_focus text,
 grounding_start_ms integer check(grounding_start_ms>=0), grounding_end_ms integer check(grounding_end_ms>=grounding_start_ms), source_observation_ids uuid[] not null default '{}', report_evidence_selected boolean not null default false,
 created_at timestamptz not null default now(), unique(session_id,sequence), unique(id,session_id,user_id), foreign key(session_id,user_id) references public.practice_sessions(id,user_id) on delete cascade
);
create table public.actor_corrections (
 id uuid primary key, session_id uuid not null, user_id uuid not null, observation_id uuid not null, content text not null check(length(trim(content))>0), correction_by_turn_id uuid not null,
 created_at timestamptz not null default now(), unique(session_id,observation_id), foreign key(session_id,user_id) references public.practice_sessions(id,user_id) on delete cascade,
 foreign key(observation_id,session_id,user_id) references public.observations(id,session_id,user_id) on delete cascade,
 foreign key(correction_by_turn_id,session_id,user_id) references public.interview_turns(id,session_id,user_id) on delete cascade
);
create table public.ai_reports (
 session_id uuid primary key, user_id uuid not null, source_run_id uuid not null unique, schema_version text not null check(schema_version='report.v1'), completion_reason text not null,
 one_line_summary jsonb not null, primary_review_point jsonb not null, confirmed_evidence jsonb not null, actor_discovery jsonb not null, grounded_encouragement jsonb not null, next_practice_step jsonb not null,
 created_at timestamptz not null default now(), foreign key(session_id,user_id) references public.practice_sessions(id,user_id) on delete cascade, foreign key(source_run_id,session_id,user_id) references public.ai_runs(id,session_id,user_id),
 check(one_line_summary->>'status'='confirmed' and length(trim(one_line_summary->>'content'))>0),
 check(primary_review_point->>'status'='confirmed' and length(trim(primary_review_point->>'content'))>0),
 check(confirmed_evidence->>'status'='confirmed' and length(trim(confirmed_evidence->>'content'))>0)
);
create table public.session_deletion_attempts (
 request_id uuid primary key, session_id uuid not null, user_id uuid not null, status text not null check(status in ('running','failed','completed')),
 storage_deleted boolean not null default false, rows_deleted boolean not null default false, safe_error_code text, attempt integer not null default 1 check(attempt>0),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(status<>'completed' or (storage_deleted and rows_deleted and safe_error_code is null))
);

alter table public.observations add constraint observations_source_run_fk foreign key(source_run_id,session_id,user_id) references public.ai_runs(id,session_id,user_id) on delete cascade;
create unique index observations_one_accepted_uidx on public.observations(session_id) where confirmation_state='accepted';
create unique index observations_session_candidate_uidx on public.observations(session_id,candidate_id) where candidate_id is not null;
create unique index ai_runs_one_active_stage_uidx on public.ai_runs(session_id,stage) where status in ('pending','running');
create index ai_runs_session_stage_created_idx on public.ai_runs(session_id,stage,created_at desc);
create index ai_runs_failed_retry_idx on public.ai_runs(status,retryable,updated_at) where status='failed' and retryable;
create index observations_session_priority_idx on public.observations(session_id,priority);
create index observations_confirmation_idx on public.observations(session_id,confirmation_state,blocked_for_questioning);
create index interview_turns_session_sequence_idx on public.interview_turns(session_id,sequence);
create index interview_turns_report_evidence_idx on public.interview_turns(session_id,report_evidence_selected) where report_evidence_selected;
create index actor_corrections_session_idx on public.actor_corrections(session_id,created_at);
create index session_deletion_reconcile_idx on public.practice_sessions(deletion_status,delete_updated_at) where deletion_status<>'active';
create index session_deletion_attempts_reconcile_idx on public.session_deletion_attempts(status,updated_at) where status in ('failed','running');

alter table public.ai_session_summaries enable row level security; alter table public.ai_runs enable row level security; alter table public.actor_corrections enable row level security;
alter table public.interview_turns enable row level security; alter table public.ai_reports enable row level security; alter table public.session_deletion_attempts enable row level security;
revoke insert,update,delete on public.ai_session_summaries,public.ai_runs,public.actor_corrections,public.interview_turns,public.ai_reports,public.session_deletion_attempts from anon,authenticated;
grant select on public.ai_session_summaries,public.ai_runs,public.actor_corrections,public.interview_turns,public.ai_reports to authenticated;

do $$ declare t text; begin foreach t in array array['ai_session_summaries','ai_runs','actor_corrections','interview_turns','ai_reports'] loop
 execute format('create policy %I on public.%I for select to authenticated using (user_id=auth.uid() and exists(select 1 from public.practice_sessions s where s.id=session_id and s.user_id=auth.uid() and s.hidden_at is null and s.deletion_status=''active'' and public.is_active_acttub_profile(auth.uid())))',t||'_owner_select',t);
end loop; end $$;

create policy practice_sessions_pipeline_active_select on public.practice_sessions as restrictive for select to authenticated using (deletion_status='active');
create policy practice_takes_pipeline_active_select on public.practice_takes as restrictive for select to authenticated using (exists(select 1 from public.practice_sessions s where s.id=session_id and s.deletion_status='active'));
create policy observations_pipeline_active_select on public.observations as restrictive for select to authenticated using (exists(select 1 from public.practice_sessions s where s.id=session_id and s.deletion_status='active'));

-- All mutation functions are service-role transaction boundaries. Each locks and owner-checks the session.
create or replace function public.acttub_claim_ai_run(p_session_id uuid,p_user_id uuid,p_stage text,p_run_id uuid,p_idempotency_key text,p_max_attempts integer,p_request_schema_version text,p_model text,p_prompt_version text)
returns setof public.ai_runs language plpgsql security definer set search_path=public as $$ declare existing public.ai_runs; begin
 perform 1 from public.practice_sessions s where s.id=p_session_id and s.user_id=p_user_id and s.pipeline_version='ai-pipeline.v1' and s.deletion_status='active' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'pipeline_session_not_found'; end if;
 select * into existing from public.ai_runs where session_id=p_session_id and stage=p_stage and idempotency_key=p_idempotency_key for update;
 if found then if existing.status in ('completed','running','pending') then return next existing; return; end if; if not existing.retryable or existing.attempt>=existing.max_attempts then raise exception 'run_not_retryable'; end if;
 return query update public.ai_runs set id=p_run_id,status='running',attempt=attempt+1,safe_error_code=null,retryable=false,started_at=now(),completed_at=null,updated_at=now() where ai_runs.id=existing.id returning *; return; end if;
 return query insert into public.ai_runs(id,session_id,user_id,stage,status,idempotency_key,attempt,max_attempts,request_schema_version,model,prompt_version,started_at) values(p_run_id,p_session_id,p_user_id,p_stage,'running',p_idempotency_key,1,p_max_attempts,p_request_schema_version,p_model,p_prompt_version,now()) returning *;
end $$;
create or replace function public.acttub_fail_ai_run(p_session_id uuid,p_user_id uuid,p_run_id uuid,p_safe_error_code text,p_retryable boolean)
returns setof public.ai_runs language plpgsql security definer set search_path=public as $$ begin
 return query update public.ai_runs set status='failed',safe_error_code=p_safe_error_code,retryable=p_retryable,completed_at=now(),updated_at=now()
 where id=p_run_id and session_id=p_session_id and user_id=p_user_id and status='running' and p_safe_error_code in ('AI_TIMEOUT','AI_UNAVAILABLE','AI_INVALID_RESPONSE','AI_INTERNAL','DELETE_STORAGE_FAILED','DELETE_ROWS_FAILED') returning *; if not found then raise exception 'invalid_failure_transition'; end if; end $$;
create or replace function public.acttub_confirm_observation(p_session_id uuid,p_user_id uuid,p_observation_id uuid,p_state text,p_correction text default null,p_correction_id uuid default null,p_turn_id uuid default null)
returns setof public.observations language plpgsql security definer set search_path=public as $$ declare seq integer; begin
 perform 1 from public.practice_sessions where id=p_session_id and user_id=p_user_id and deletion_status='active' for update; if not found then raise exception 'session_not_found'; end if;
 if p_state not in ('accepted','rejected','unsure') or (p_correction is not null and (p_state<>'rejected' or length(trim(p_correction))=0)) then raise exception 'invalid_confirmation'; end if;
 if p_correction is not null then select coalesce(max(sequence)+1,0) into seq from public.interview_turns where session_id=p_session_id;
 insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content) values(p_turn_id,p_session_id,p_user_id,seq,'actor','actor_correction',p_correction);
 insert into public.actor_corrections(id,session_id,user_id,observation_id,content,correction_by_turn_id) values(p_correction_id,p_session_id,p_user_id,p_observation_id,p_correction,p_turn_id);
 end if; return query update public.observations set confirmation_state=p_state,blocked_for_questioning=(p_state<>'accepted') where id=p_observation_id and session_id=p_session_id and user_id=p_user_id returning *; end $$;
create or replace function public.acttub_begin_session_delete(p_session_id uuid,p_user_id uuid,p_request_id uuid)
returns setof public.session_deletion_attempts language plpgsql security definer set search_path=public as $$ begin
 perform 1 from public.practice_sessions where id=p_session_id and user_id=p_user_id and (delete_request_id is null or delete_request_id=p_request_id) for update; if not found and exists(select 1 from public.practice_sessions where id=p_session_id and user_id=p_user_id) then raise exception 'delete_request_conflict'; end if; if not found then return query select * from public.session_deletion_attempts where request_id=p_request_id and session_id=p_session_id and user_id=p_user_id; return; end if;
 update public.practice_sessions set deletion_status='deleting',delete_request_id=p_request_id,delete_started_at=coalesce(delete_started_at,now()),delete_updated_at=now() where id=p_session_id;
 if exists(select 1 from public.session_deletion_attempts where request_id=p_request_id and (session_id<>p_session_id or user_id<>p_user_id)) then raise exception 'delete_request_conflict'; end if; return query insert into public.session_deletion_attempts(request_id,session_id,user_id,status) values(p_request_id,p_session_id,p_user_id,'running') on conflict(request_id) do update set attempt=session_deletion_attempts.attempt+1,updated_at=now() where session_deletion_attempts.session_id=p_session_id and session_deletion_attempts.user_id=p_user_id returning *; end $$;
create or replace function public.acttub_record_storage_deleted(p_session_id uuid,p_user_id uuid,p_request_id uuid)
returns setof public.session_deletion_attempts language sql security definer set search_path=public as $$ update public.session_deletion_attempts set storage_deleted=true,updated_at=now() where request_id=p_request_id and session_id=p_session_id and user_id=p_user_id returning * $$;
create or replace function public.acttub_fail_session_delete(p_session_id uuid,p_user_id uuid,p_request_id uuid,p_safe_error_code text)
returns setof public.session_deletion_attempts language plpgsql security definer set search_path=public as $$ begin if p_safe_error_code not in ('DELETE_STORAGE_FAILED','DELETE_ROWS_FAILED','DELETE_VERIFICATION_FAILED') then raise exception 'invalid_delete_error'; end if; perform 1 from public.session_deletion_attempts where request_id=p_request_id and session_id=p_session_id and user_id=p_user_id for update; if not found then raise exception 'delete_attempt_not_found'; end if; update public.practice_sessions set deletion_status='delete_failed',delete_error_code=p_safe_error_code,delete_updated_at=now() where id=p_session_id and user_id=p_user_id; return query update public.session_deletion_attempts set status='failed',safe_error_code=p_safe_error_code,updated_at=now() where request_id=p_request_id and session_id=p_session_id and user_id=p_user_id returning *; end $$;
create or replace function public.acttub_complete_session_delete(p_session_id uuid,p_user_id uuid,p_request_id uuid)
returns setof public.session_deletion_attempts language plpgsql security definer set search_path=public as $$ begin
 perform 1 from public.session_deletion_attempts where request_id=p_request_id and session_id=p_session_id and user_id=p_user_id and storage_deleted for update; if not found then raise exception 'storage_not_verified'; end if;
 delete from public.practice_sessions where id=p_session_id and user_id=p_user_id; if exists(select 1 from public.practice_takes where session_id=p_session_id) or exists(select 1 from public.observations where session_id=p_session_id) or exists(select 1 from public.interview_turns where session_id=p_session_id) or exists(select 1 from public.ai_runs where session_id=p_session_id) or exists(select 1 from public.ai_reports where session_id=p_session_id) then raise exception 'delete_orphan_detected'; end if; return query update public.session_deletion_attempts set status='completed',rows_deleted=true,safe_error_code=null,updated_at=now() where request_id=p_request_id returning *; end $$;

-- Payload-heavy boundaries validate and persist their complete transaction atomically.
create or replace function public.acttub_finalize_ai_upload(p_upload_intent_id uuid,p_user_id uuid,p_duration_ms integer,p_media_metadata_version text)
returns setof public.upload_intents language plpgsql security definer set search_path=public as $$ begin
 if p_duration_ms not between 1 and 300000 or p_media_metadata_version<>'iso-bmff-duration.v1' then raise exception 'invalid_media_metadata'; end if;
 return query update public.upload_intents set status='finalized',authoritative_duration_ms=p_duration_ms,media_metadata_version=p_media_metadata_version,ai_eligible_at=now(),finalized_at=now(),updated_at=now()
 where id=p_upload_intent_id and user_id=p_user_id and status='created' and required_consent_version_snapshot=public.current_acttub_terms_version() and ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and adult_confirmed_at is not null and all_participants_confirmed_at is not null and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) returning *;
 if not found then raise exception 'upload_not_eligible'; end if; end $$;
create or replace function public.acttub_create_pipeline_session(p_upload_intent_id uuid,p_user_id uuid,p_session_id uuid,p_take_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare u public.upload_intents; begin
 select * into u from public.upload_intents where id=p_upload_intent_id and user_id=p_user_id and status='finalized' and ai_eligible_at is not null and authoritative_duration_ms between 1 and 300000 and media_metadata_version='iso-bmff-duration.v1' and required_consent_version_snapshot=public.current_acttub_terms_version() and ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'upload_not_ai_eligible'; end if;
 if u.session_id<>p_session_id then raise exception 'idempotency_conflict'; end if; if exists(select 1 from public.practice_sessions where id=p_session_id) then return jsonb_build_object('session_id',p_session_id,'take_id',p_take_id); end if;
 insert into public.practice_sessions(id,user_id,upload_intent_id,status,medium,genre,situation,character_context,subtext,pipeline_version,required_consent_version_snapshot,ai_processing_consent_version_snapshot,adult_confirmed_at,all_participants_confirmed_at,interview_status,substantive_answer_count)
 values(p_session_id,p_user_id,p_upload_intent_id,'observations_pending',coalesce(p_payload->>'medium','upload_url'),p_payload->>'genre',p_payload->>'situation',p_payload->>'characterContext',p_payload->>'subtext','ai-pipeline.v1',u.required_consent_version_snapshot,u.ai_processing_consent_version_snapshot,u.adult_confirmed_at,u.all_participants_confirmed_at,'active',0);
 insert into public.practice_takes(id,session_id,user_id,storage_bucket,storage_path,mime_type,size_bytes,duration_ms,media_metadata_version,analysis_status) values(p_take_id,p_session_id,p_user_id,u.expected_storage_bucket,u.expected_storage_path,u.expected_mime_type,u.expected_size_bytes,u.authoritative_duration_ms,u.media_metadata_version,'generated');
 update public.upload_intents set updated_at=now() where id=p_upload_intent_id; return jsonb_build_object('session_id',p_session_id,'take_id',p_take_id); end $$;
create or replace function public.acttub_complete_summary_run(p_session_id uuid,p_user_id uuid,p_run_id uuid,p_summary jsonb,p_candidates jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare c jsonb; a jsonb; take uuid; duration integer; existing_run uuid; idx integer; expected_start integer; expected_end integer; begin
 select source_run_id into existing_run from public.ai_session_summaries where session_id=p_session_id and user_id=p_user_id for update; if found then return (select jsonb_build_object('sessionId',s.session_id,'sourceRunId',s.source_run_id,'normalizedSummary',s.normalized_summary,'observationCandidates',coalesce(jsonb_agg(jsonb_build_object('id',o.candidate_id,'startMs',o.timestamp_start_ms,'endMs',o.timestamp_end_ms,'text',o.observation_text,'priority',o.priority,'dimension',o.dimension,'severity',o.severity) order by o.priority) filter(where o.id is not null),'[]'::jsonb)) from public.ai_session_summaries s left join public.observations o on o.session_id=s.session_id and o.source_run_id=s.source_run_id where s.session_id=p_session_id and s.user_id=p_user_id group by s.session_id,s.source_run_id,s.normalized_summary); end if;
 perform 1 from public.ai_runs r join public.practice_sessions s on s.id=r.session_id and s.user_id=r.user_id where r.id=p_run_id and r.session_id=p_session_id and r.user_id=p_user_id and r.stage='summary' and r.status='running' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'run_not_running'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_summary) k)<>array['anomalies','intentAlignment','keyDimension','keyMoment','observation','schemaVersion','subtextStatus','summary'] or p_summary->>'schemaVersion'<>'scene-summary.v1' or p_summary->>'subtextStatus' not in ('provided','not_provided') or jsonb_typeof(p_summary->'anomalies')<>'array' or jsonb_typeof(p_candidates)<>'array' or jsonb_array_length(p_candidates)<>jsonb_array_length(p_summary->'anomalies') or length(trim(p_summary->>'summary'))=0 then raise exception 'invalid_summary'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_summary->'observation') k)<>array['dialogue','emotion','expression','extra','movement','pitch','tempo','timeline'] or jsonb_typeof(p_summary->'observation'->'extra')<>'array' or exists(select 1 from jsonb_each(p_summary->'observation') e where e.key<>'extra' and (jsonb_typeof(e.value)<>'string' or length(trim(e.value#>>'{}'))=0)) or exists(select 1 from jsonb_array_elements(p_summary->'observation'->'extra') x where jsonb_typeof(x)<>'object' or (select array_agg(k order by k) from jsonb_object_keys(x) k)<>array['name','observation'] or jsonb_typeof(x->'name')<>'string' or length(trim(x->>'name'))=0 or jsonb_typeof(x->'observation')<>'string' or length(trim(x->>'observation'))=0) then raise exception 'invalid_summary_observation'; end if;
 if exists(select 1 from (values(p_summary->'intentAlignment'),(p_summary->'keyMoment'),(p_summary->'keyDimension')) v(x) where jsonb_typeof(x) not in ('null','string') or (jsonb_typeof(x)='string' and length(trim(x#>>'{}'))=0)) or (p_summary->>'subtextStatus'='not_provided' and (p_summary->'intentAlignment'<>'null'::jsonb or p_summary->'keyMoment'<>'null'::jsonb or p_summary->'keyDimension'<>'null'::jsonb)) then raise exception 'invalid_summary_nullable'; end if;
 if (p_summary->>'subtextStatus')<>(select case when nullif(trim(subtext),'') is null then 'not_provided' else 'provided' end from public.practice_sessions where id=p_session_id and user_id=p_user_id) then raise exception 'summary_subtext_mismatch'; end if; select id,duration_ms into take,duration from public.practice_takes where session_id=p_session_id and user_id=p_user_id order by created_at limit 1; if take is null then raise exception 'take_not_found'; end if;
 insert into public.ai_session_summaries(session_id,user_id,take_id,schema_version,subtext_status,normalized_summary,source_run_id) values(p_session_id,p_user_id,take,'scene-summary.v1',p_summary->>'subtextStatus',p_summary,p_run_id);
 for c,idx in select value,ordinality::integer from jsonb_array_elements(p_candidates) with ordinality loop a:=p_summary->'anomalies'->(idx-1); if (select array_agg(k order by k) from jsonb_object_keys(a) k)<>array['dimension','end','impactOnIntent','intentImpact','likelyCause','onKeyDimension','overlapsKeyMoment','severity','severityReason','start','what','whyOdd'] or (a->>'start')!~'^[0-9]{2,}:[0-5][0-9]$' or (a->>'end')!~'^[0-9]{2,}:[0-5][0-9]$' or jsonb_typeof(a->'dimension')<>'string' or length(trim(a->>'dimension'))=0 or jsonb_typeof(a->'what')<>'string' or length(trim(a->>'what'))=0 or exists(select 1 from (values(a->'whyOdd'),(a->'likelyCause'),(a->'impactOnIntent'),(a->'severityReason')) v(x) where jsonb_typeof(x) not in ('null','string') or (jsonb_typeof(x)='string' and length(trim(x#>>'{}'))=0)) or jsonb_typeof(a->'overlapsKeyMoment') not in ('null','boolean') or jsonb_typeof(a->'onKeyDimension') not in ('null','boolean') or (a->'intentImpact'<>'null'::jsonb and a->>'intentImpact' not in ('반전','약화','국소')) or (a->'severity'<>'null'::jsonb and a->>'severity' not in ('high','mid','low')) or (p_summary->>'subtextStatus'='not_provided' and exists(select 1 from (values(a->'whyOdd'),(a->'likelyCause'),(a->'impactOnIntent'),(a->'overlapsKeyMoment'),(a->'onKeyDimension'),(a->'intentImpact'),(a->'severity'),(a->'severityReason')) v(x) where x<>'null'::jsonb)) then raise exception 'invalid_summary_anomaly'; end if; expected_start:=((split_part(a->>'start',':',1)::integer*60)+split_part(a->>'start',':',2)::integer)*1000; expected_end:=((split_part(a->>'end',':',1)::integer*60)+split_part(a->>'end',':',2)::integer)*1000; if expected_start>expected_end then raise exception 'invalid_summary_anomaly_range'; end if; expected_start:=least(expected_start,duration); expected_end:=least(expected_end,duration); if (select array_agg(k order by k) from jsonb_object_keys(c) k)<>array['dimension','endMs','id','priority','severity','startMs','text'] or (c->>'priority')::integer<>idx or c->>'text'<>a->>'what' or c->>'dimension'<>a->>'dimension' or c->'severity' is distinct from a->'severity' or (c->>'startMs')::integer<>expected_start or (c->>'endMs')::integer<>expected_end then raise exception 'invalid_summary_candidate'; end if;
 insert into public.observations(id,session_id,take_id,user_id,timestamp_start_ms,timestamp_end_ms,observation_text,confidence,confirmation_state,blocked_for_questioning,candidate_id,priority,dimension,severity,source_run_id) values((c->>'id')::uuid,p_session_id,take,p_user_id,(c->>'startMs')::integer,(c->>'endMs')::integer,c->>'text',null,'unasked',false,(c->>'id')::uuid,idx,c->>'dimension',c->>'severity',p_run_id); end loop;
 update public.ai_runs set status='completed',response_schema_version='summary-response.v1',safe_error_code=null,completed_at=now(),updated_at=now() where id=p_run_id; return jsonb_build_object('session_id',p_session_id,'run_id',p_run_id); end $$;
create or replace function public.acttub_append_pipeline_turn(p_session_id uuid,p_user_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare expected integer; actor jsonb; agent jsonb; begin
 select substantive_answer_count into expected from public.practice_sessions s where s.id=p_session_id and s.user_id=p_user_id and s.interview_status in ('active','paused') and s.deletion_status='active' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found or expected<>(p_payload->>'expectedSubstantiveAnswerCount')::integer or expected>=10 then raise exception 'turn_conflict'; end if;
 actor:=p_payload->'actorTurn'; agent:=p_payload->'agentTurn';
 if p_payload->'currentInput'->>'command' not in ('start','observation_update','answer','manual_stop','resume') or ((p_payload->'currentInput'->>'command') in ('start','observation_update','manual_stop','resume') and actor<>'null'::jsonb) or ((p_payload->'currentInput'->>'command')='resume' and not exists(select 1 from public.practice_sessions where id=p_session_id and interview_status='paused')) then raise exception 'invalid_current_input'; end if;
 if jsonb_array_length(p_payload->'reportEvidence'->'observationIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x) or jsonb_array_length(p_payload->'reportEvidence'->'answerTurnIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x where not exists(select 1 from public.interview_turns t where t.id=x::uuid and t.session_id=p_session_id and t.user_id=p_user_id and t.role='actor' and t.kind='answer' and t.report_evidence_selected)) then raise exception 'invalid_report_evidence'; end if;
 if (p_payload->'currentInput'->>'command')='answer' and (actor is null or actor='null'::jsonb or actor->>'kind' not in ('answer','unknown') or p_payload->'currentInput'->>'answerTurnId'<>actor->>'id' or p_payload->'currentInput'->>'answer'<>actor->>'content') then raise exception 'current_input_mismatch'; end if;
 if actor is not null and actor<>'null'::jsonb then if actor->>'kind' not in ('answer','unknown') or (actor->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) then raise exception 'invalid_actor_turn'; end if; insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,source_observation_ids,report_evidence_selected) values((actor->>'id')::uuid,p_session_id,p_user_id,(actor->>'sequence')::integer,'actor',actor->>'kind',actor->>'content',array(select jsonb_array_elements_text(actor->'sourceObservationIds'))::uuid[],coalesce((actor->>'reportEvidenceSelected')::boolean,false)); expected:=expected+1; end if;
 if (agent->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) or agent->>'kind' not in ('question','closing') then raise exception 'invalid_agent_turn'; end if;
 if exists(select 1 from jsonb_array_elements_text(agent->'sourceObservationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) then raise exception 'invalid_source_observation'; end if;
 insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,question_focus,source_observation_ids) values((agent->>'id')::uuid,p_session_id,p_user_id,(agent->>'sequence')::integer,'agent',agent->>'kind',agent->>'content',agent->>'questionFocus',array(select jsonb_array_elements_text(agent->'sourceObservationIds'))::uuid[]);
 update public.practice_sessions set substantive_answer_count=expected,interview_status='active',report_evidence_observation_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds'))::uuid[],report_evidence_answer_turn_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds'))::uuid[],updated_at=now() where id=p_session_id; update public.ai_runs set status='completed',response_schema_version='agent-turn.v1',completed_at=now(),updated_at=now() where id=(p_payload->>'agentRunId')::uuid and session_id=p_session_id and user_id=p_user_id and stage='agent' and status='running'; if not found then raise exception 'agent_run_not_running'; end if; return jsonb_build_object('substantive_answer_count',expected); end $$;
create or replace function public.acttub_complete_interview(p_session_id uuid,p_user_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare reason text:=p_payload->>'completionReason'; stat text:=p_payload->>'status'; obs uuid[]:=array(select jsonb_array_elements_text(p_payload->'observationIds'))::uuid[]; turns uuid[]:=array(select jsonb_array_elements_text(p_payload->'answerTurnIds'))::uuid[]; n integer; prior text; begin
 select substantive_answer_count,interview_status into n,prior from public.practice_sessions where id=p_session_id and user_id=p_user_id and deletion_status='active' and interview_status in ('active','paused') for update; if not found then raise exception 'session_not_mutable'; end if;
 if (stat='completed' and reason not in ('interview_complete_report_ready','manual_stop_report_ready','hard_limit_report_ready')) or (stat='paused' and reason<>'manual_stop_paused') or (stat='completed_without_report' and reason not in ('insufficient_confirmed_evidence','insufficient_interview_evidence')) then raise exception 'invalid_completion'; end if;
 if reason='interview_complete_report_ready' and n<5 or reason='hard_limit_report_ready' and n<>10 or reason='insufficient_interview_evidence' and n<10 then raise exception 'invalid_completion_count'; end if;
 if cardinality(obs)<>cardinality(array(select distinct x from unnest(obs) x)) or cardinality(turns)<>cardinality(array(select distinct x from unnest(turns) x)) then raise exception 'duplicate_report_evidence'; end if;
 if stat='completed' then if cardinality(obs)=0 or cardinality(turns)=0 or exists(select 1 from unnest(obs) x where not exists(select 1 from public.observations o where o.id=x and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) or exists(select 1 from unnest(turns) x where not exists(select 1 from public.interview_turns t where t.id=x and t.session_id=p_session_id and t.user_id=p_user_id and t.role='actor' and t.kind='answer' and length(trim(t.content))>0 and t.report_evidence_selected)) then raise exception 'invalid_report_evidence'; end if; else if cardinality(obs)<>0 or cardinality(turns)<>0 then raise exception 'evidence_not_allowed'; end if; end if;
 update public.practice_sessions set interview_status=stat,completion_reason=reason,report_evidence_observation_ids=obs,report_evidence_answer_turn_ids=turns,updated_at=now() where id=p_session_id; return jsonb_build_object('status',stat,'completion_reason',reason); end $$;
create or replace function public.acttub_complete_report_run(p_session_id uuid,p_user_id uuid,p_run_id uuid,p_report jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare sec jsonb:=p_report->'sections'; existing public.ai_reports; e record; range jsonb; begin
 select * into existing from public.ai_reports where session_id=p_session_id and user_id=p_user_id for update; if found then return jsonb_build_object('schemaVersion',existing.schema_version,'sections',jsonb_build_object('oneLineSummary',existing.one_line_summary,'primaryReviewPoint',existing.primary_review_point,'confirmedEvidence',existing.confirmed_evidence,'actorDiscovery',existing.actor_discovery,'groundedEncouragement',existing.grounded_encouragement,'nextPracticeStep',existing.next_practice_step)); end if;
 perform 1 from public.ai_runs r join public.practice_sessions s on s.id=r.session_id and s.user_id=r.user_id where r.id=p_run_id and r.session_id=p_session_id and r.user_id=p_user_id and r.stage='report' and r.status='running' and s.interview_status='completed' and s.completion_reason in ('interview_complete_report_ready','manual_stop_report_ready','hard_limit_report_ready') and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'report_not_ready'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_report) k)<>array['schemaVersion','sections'] or p_report->>'schemaVersion'<>'report.v1' or (select array_agg(k order by k) from jsonb_object_keys(sec) k)<>array['actorDiscovery','confirmedEvidence','groundedEncouragement','nextPracticeStep','oneLineSummary','primaryReviewPoint'] then raise exception 'invalid_report'; end if;
 for e in select key,value from jsonb_each(sec) loop if (select array_agg(k order by k) from jsonb_object_keys(e.value) k)<>array['content','observationEvidenceIds','status','timestampRange','turnEvidenceIds'] or e.value->>'status' not in ('confirmed','not_confirmed') then raise exception 'invalid_report_section'; end if; if e.value->>'status'='not_confirmed' then if e.key in ('oneLineSummary','primaryReviewPoint','confirmedEvidence') or e.value->'content'<>'null'::jsonb or e.value->'timestampRange'<>'null'::jsonb or jsonb_array_length(e.value->'observationEvidenceIds')<>0 or jsonb_array_length(e.value->'turnEvidenceIds')<>0 then raise exception 'invalid_unconfirmed_section'; end if; else if length(trim(e.value->>'content'))=0 or jsonb_array_length(e.value->'observationEvidenceIds')+jsonb_array_length(e.value->'turnEvidenceIds')=0 then raise exception 'invalid_confirmed_section'; end if; end if;
 if e.value->>'status'='confirmed' and ((e.key in ('oneLineSummary','confirmedEvidence') and (jsonb_array_length(e.value->'observationEvidenceIds')=0 or jsonb_array_length(e.value->'turnEvidenceIds')=0)) or (e.key='primaryReviewPoint' and (jsonb_array_length(e.value->'observationEvidenceIds')=0 or e.value->'timestampRange'='null'::jsonb)) or (e.key='actorDiscovery' and jsonb_array_length(e.value->'turnEvidenceIds')=0) or (e.key='groundedEncouragement' and jsonb_array_length(e.value->'observationEvidenceIds')=0)) then raise exception 'invalid_section_evidence'; end if;
 if exists(select 1 from jsonb_array_elements_text(e.value->'observationEvidenceIds') x where not exists(select 1 from public.practice_sessions s join public.observations o on o.session_id=s.id and o.user_id=s.user_id where s.id=p_session_id and o.id=x::uuid and o.confirmation_state='accepted' and not o.blocked_for_questioning and o.id=any(s.report_evidence_observation_ids))) or exists(select 1 from jsonb_array_elements_text(e.value->'turnEvidenceIds') x where not exists(select 1 from public.practice_sessions s join public.interview_turns t on t.session_id=s.id and t.user_id=s.user_id where s.id=p_session_id and t.id=x::uuid and (t.id=any(s.report_evidence_answer_turn_ids) or t.kind='actor_correction'))) then raise exception 'invalid_report_evidence'; end if;
 range:=e.value->'timestampRange'; if range<>'null'::jsonb and ((select array_agg(k order by k) from jsonb_object_keys(range) k)<>array['endMs','startMs'] or (range->>'endMs')::integer<(range->>'startMs')::integer or not exists(select 1 from jsonb_array_elements_text(e.value->'observationEvidenceIds') x join public.observations o on o.id=x::uuid and o.session_id=p_session_id where o.timestamp_start_ms=(range->>'startMs')::integer and o.timestamp_end_ms=(range->>'endMs')::integer) and (e.key='primaryReviewPoint' or not exists(select 1 from jsonb_array_elements_text(e.value->'turnEvidenceIds') x join public.actor_corrections c on c.correction_by_turn_id=x::uuid and c.session_id=p_session_id join public.observations o on o.id=c.observation_id where o.timestamp_start_ms=(range->>'startMs')::integer and o.timestamp_end_ms=(range->>'endMs')::integer))) then raise exception 'invalid_report_timestamp'; end if; end loop;
 insert into public.ai_reports(session_id,user_id,source_run_id,schema_version,completion_reason,one_line_summary,primary_review_point,confirmed_evidence,actor_discovery,grounded_encouragement,next_practice_step) select p_session_id,p_user_id,p_run_id,'report.v1',completion_reason,sec->'oneLineSummary',sec->'primaryReviewPoint',sec->'confirmedEvidence',sec->'actorDiscovery',sec->'groundedEncouragement',sec->'nextPracticeStep' from public.practice_sessions where id=p_session_id;
 update public.ai_runs set status='completed',response_schema_version='report.v1',completed_at=now(),updated_at=now() where id=p_run_id and session_id=p_session_id and user_id=p_user_id and status='running'; if not found then raise exception 'report_run_conflict'; end if; return p_report; end $$;

revoke execute on function public.current_acttub_ai_processing_consent_version() from public,anon,authenticated; grant execute on function public.current_acttub_ai_processing_consent_version() to service_role;
revoke execute on function public.acttub_finalize_ai_upload(uuid,uuid,integer,text) from public,anon,authenticated; grant execute on function public.acttub_finalize_ai_upload(uuid,uuid,integer,text) to service_role;

-- Exact signature privilege boundary for every pipeline function.
revoke execute on function public.acttub_create_pipeline_session(uuid,uuid,uuid,uuid,jsonb), public.acttub_claim_ai_run(uuid,uuid,text,uuid,text,integer,text,text,text), public.acttub_complete_summary_run(uuid,uuid,uuid,jsonb,jsonb), public.acttub_confirm_observation(uuid,uuid,uuid,text,text,uuid,uuid), public.acttub_append_pipeline_turn(uuid,uuid,jsonb), public.acttub_complete_interview(uuid,uuid,jsonb), public.acttub_complete_report_run(uuid,uuid,uuid,jsonb), public.acttub_fail_ai_run(uuid,uuid,uuid,text,boolean), public.acttub_begin_session_delete(uuid,uuid,uuid), public.acttub_record_storage_deleted(uuid,uuid,uuid), public.acttub_complete_session_delete(uuid,uuid,uuid), public.acttub_fail_session_delete(uuid,uuid,uuid,text) from public,anon,authenticated;
grant execute on function public.acttub_create_pipeline_session(uuid,uuid,uuid,uuid,jsonb), public.acttub_claim_ai_run(uuid,uuid,text,uuid,text,integer,text,text,text), public.acttub_complete_summary_run(uuid,uuid,uuid,jsonb,jsonb), public.acttub_confirm_observation(uuid,uuid,uuid,text,text,uuid,uuid), public.acttub_append_pipeline_turn(uuid,uuid,jsonb), public.acttub_complete_interview(uuid,uuid,jsonb), public.acttub_complete_report_run(uuid,uuid,uuid,jsonb), public.acttub_fail_ai_run(uuid,uuid,uuid,text,boolean), public.acttub_begin_session_delete(uuid,uuid,uuid), public.acttub_record_storage_deleted(uuid,uuid,uuid), public.acttub_complete_session_delete(uuid,uuid,uuid), public.acttub_fail_session_delete(uuid,uuid,uuid,text) to service_role;
