-- Preserve unknown actor turns without advancing substantive answer count.
create or replace function public.acttub_append_pipeline_turn(p_session_id uuid,p_user_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare expected integer; actor jsonb; agent jsonb; begin
 select substantive_answer_count into expected from public.practice_sessions s where s.id=p_session_id and s.user_id=p_user_id and s.interview_status in ('active','paused') and s.deletion_status='active' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found or expected<>(p_payload->>'expectedSubstantiveAnswerCount')::integer or expected>=10 then raise exception 'turn_conflict'; end if;
 actor:=p_payload->'actorTurn'; agent:=p_payload->'agentTurn';
 if p_payload->'currentInput'->>'command' not in ('start','observation_update','answer','manual_stop','resume') or ((p_payload->'currentInput'->>'command') in ('start','observation_update','manual_stop','resume') and actor<>'null'::jsonb) or ((p_payload->'currentInput'->>'command')='resume' and not exists(select 1 from public.practice_sessions where id=p_session_id and interview_status='paused')) then raise exception 'invalid_current_input'; end if;
 if jsonb_array_length(p_payload->'reportEvidence'->'observationIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x) or jsonb_array_length(p_payload->'reportEvidence'->'answerTurnIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x where not exists(select 1 from public.interview_turns t where t.id=x::uuid and t.session_id=p_session_id and t.user_id=p_user_id and t.role='actor' and t.kind='answer' and t.report_evidence_selected) and not (actor is not null and actor<>'null'::jsonb and actor->>'id'=x and actor->>'kind'='answer' and coalesce((actor->>'reportEvidenceSelected')::boolean,false))) then raise exception 'invalid_report_evidence'; end if;
 if (p_payload->'currentInput'->>'command')='answer' and (actor is null or actor='null'::jsonb or actor->>'kind' not in ('answer','unknown') or p_payload->'currentInput'->>'answerTurnId'<>actor->>'id' or p_payload->'currentInput'->>'answer'<>actor->>'content') then raise exception 'current_input_mismatch'; end if;
 if actor is not null and actor<>'null'::jsonb then if actor->>'kind' not in ('answer','unknown') or (actor->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) then raise exception 'invalid_actor_turn'; end if; insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,source_observation_ids,report_evidence_selected) values((actor->>'id')::uuid,p_session_id,p_user_id,(actor->>'sequence')::integer,'actor',actor->>'kind',actor->>'content',array(select jsonb_array_elements_text(actor->'sourceObservationIds'))::uuid[],coalesce((actor->>'reportEvidenceSelected')::boolean,false)); if actor->>'kind'='answer' then expected:=expected+1; end if; end if;
 if (agent->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) or agent->>'kind' not in ('question','closing') then raise exception 'invalid_agent_turn'; end if;
 if exists(select 1 from jsonb_array_elements_text(agent->'sourceObservationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) then raise exception 'invalid_source_observation'; end if;
 insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,question_focus,source_observation_ids) values((agent->>'id')::uuid,p_session_id,p_user_id,(agent->>'sequence')::integer,'agent',agent->>'kind',agent->>'content',agent->>'questionFocus',array(select jsonb_array_elements_text(agent->'sourceObservationIds'))::uuid[]);
 update public.practice_sessions set substantive_answer_count=expected,interview_status='active',report_evidence_observation_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds'))::uuid[],report_evidence_answer_turn_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds'))::uuid[],updated_at=now() where id=p_session_id; update public.ai_runs set status='completed',response_schema_version='agent-turn.v1',completed_at=now(),updated_at=now() where id=(p_payload->>'agentRunId')::uuid and session_id=p_session_id and user_id=p_user_id and stage='agent' and status='running'; if not found then raise exception 'agent_run_not_running'; end if; return jsonb_build_object('substantive_answer_count',expected); end $$;
