-- Forward-only contract hardening for the AI pipeline.
-- This migration tightens source-only invariants without widening the privilege surface.

create or replace function public.acttub_confirm_observation(p_session_id uuid,p_user_id uuid,p_observation_id uuid,p_state text,p_correction text default null,p_correction_id uuid default null,p_turn_id uuid default null)
returns setof public.observations language plpgsql security definer set search_path=public as $$ declare seq integer; begin
 perform 1 from public.practice_sessions where id=p_session_id and user_id=p_user_id and deletion_status='active' and (interview_status is null or interview_status in ('active','paused')) for update; if not found then raise exception 'session_not_mutable'; end if;
 if p_state not in ('accepted','rejected','unsure') or (p_correction is not null and (p_state<>'rejected' or length(trim(p_correction))=0)) then raise exception 'invalid_confirmation'; end if;
 if p_state='accepted' and exists(select 1 from public.observations where session_id=p_session_id and user_id=p_user_id and confirmation_state='accepted' and id<>p_observation_id) then raise exception 'accepted_observation_exists'; end if;
 if p_correction is not null then select coalesce(max(sequence)+1,0) into seq from public.interview_turns where session_id=p_session_id;
  insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content) values(p_turn_id,p_session_id,p_user_id,seq,'actor','actor_correction',p_correction);
  insert into public.actor_corrections(id,session_id,user_id,observation_id,content,correction_by_turn_id) values(p_correction_id,p_session_id,p_user_id,p_observation_id,p_correction,p_turn_id);
 end if;
 return query update public.observations set confirmation_state=p_state,blocked_for_questioning=(p_state<>'accepted') where id=p_observation_id and session_id=p_session_id and user_id=p_user_id returning *;
end $$;

create or replace function public.acttub_complete_summary_run(p_session_id uuid,p_user_id uuid,p_run_id uuid,p_summary jsonb,p_candidates jsonb,p_model text,p_prompt_version text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare c jsonb; a jsonb; take uuid; duration integer; existing_run uuid; idx integer; expected_start integer; expected_end integer; begin
 select source_run_id into existing_run from public.ai_session_summaries where session_id=p_session_id and user_id=p_user_id for update; if found then return (select jsonb_build_object('sessionId',s.session_id,'sourceRunId',s.source_run_id,'normalizedSummary',s.normalized_summary,'observationCandidates',coalesce(jsonb_agg(jsonb_build_object('id',o.candidate_id,'startMs',o.timestamp_start_ms,'endMs',o.timestamp_end_ms,'text',o.observation_text,'priority',o.priority,'dimension',o.dimension,'severity',o.severity) order by o.priority) filter(where o.id is not null),'[]'::jsonb)) from public.ai_session_summaries s left join public.observations o on o.session_id=s.session_id and o.source_run_id=s.source_run_id where s.session_id=p_session_id and s.user_id=p_user_id group by s.session_id,s.source_run_id,s.normalized_summary); end if;
 perform 1 from public.ai_runs r join public.practice_sessions s on s.id=r.session_id and s.user_id=r.user_id where r.id=p_run_id and r.session_id=p_session_id and r.user_id=p_user_id and r.stage='summary' and r.status='running' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'run_not_running'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_summary) k)<>array['anomalies','intentAlignment','keyDimension','keyMoment','observation','schemaVersion','subtextStatus','summary'] or p_summary->>'schemaVersion'<>'scene-summary.v1' or p_summary->>'subtextStatus' not in ('provided','not_provided') or jsonb_typeof(p_summary->'anomalies')<>'array' or jsonb_typeof(p_candidates)<>'array' or jsonb_array_length(p_candidates)<>jsonb_array_length(p_summary->'anomalies') or length(trim(p_summary->>'summary'))=0 then raise exception 'invalid_summary'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_summary->'observation') k)<>array['dialogue','emotion','expression','extra','movement','pitch','tempo','timeline'] or jsonb_typeof(p_summary->'observation'->'extra')<>'array' or exists(select 1 from jsonb_each(p_summary->'observation') e where e.key<>'extra' and (jsonb_typeof(e.value)<>'string' or length(trim(e.value#>>'{}'))=0)) or exists(select 1 from jsonb_array_elements(p_summary->'observation'->'extra') x where jsonb_typeof(x)<>'object' or (select array_agg(k order by k) from jsonb_object_keys(x) k)<>array['name','observation'] or jsonb_typeof(x->'name')<>'string' or length(trim(x->>'name'))=0 or jsonb_typeof(x->'observation')<>'string' or length(trim(x->>'observation'))=0) then raise exception 'invalid_summary_observation'; end if;
 if exists(select 1 from (values(p_summary->'intentAlignment'),(p_summary->'keyMoment'),(p_summary->'keyDimension')) v(x) where jsonb_typeof(x) not in ('null','string') or (jsonb_typeof(x)='string' and length(trim(x#>>'{}'))=0)) or (p_summary->>'subtextStatus'='not_provided' and (p_summary->'intentAlignment'<>'null'::jsonb or p_summary->'keyMoment'<>'null'::jsonb or p_summary->'keyDimension'<>'null'::jsonb)) then raise exception 'invalid_summary_nullable'; end if;
 if (p_summary->>'subtextStatus')<>(select case when nullif(trim(subtext),'') is null then 'not_provided' else 'provided' end from public.practice_sessions where id=p_session_id and user_id=p_user_id) then raise exception 'summary_subtext_mismatch'; end if;
 select id,duration_ms into take,duration from public.practice_takes where session_id=p_session_id and user_id=p_user_id order by created_at limit 1; if take is null then raise exception 'take_not_found'; end if;
 insert into public.ai_session_summaries(session_id,user_id,take_id,schema_version,subtext_status,normalized_summary,source_run_id) values(p_session_id,p_user_id,take,'scene-summary.v1',p_summary->>'subtextStatus',p_summary,p_run_id);
 for c,idx in select value,ordinality::integer from jsonb_array_elements(p_candidates) with ordinality loop a:=p_summary->'anomalies'->(idx-1); if (select array_agg(k order by k) from jsonb_object_keys(a) k)<>array['dimension','end','impactOnIntent','intentImpact','likelyCause','onKeyDimension','overlapsKeyMoment','severity','severityReason','start','what','whyOdd'] or (a->>'start')!~'^[0-9]{2,}:[0-5][0-9]$' or (a->>'end')!~'^[0-9]{2,}:[0-5][0-9]$' or jsonb_typeof(a->'dimension')<>'string' or length(trim(a->>'dimension'))=0 or jsonb_typeof(a->'what')<>'string' or length(trim(a->>'what'))=0 or exists(select 1 from (values(a->'whyOdd'),(a->'likelyCause'),(a->'impactOnIntent'),(a->'severityReason')) v(x) where jsonb_typeof(x) not in ('null','string') or (jsonb_typeof(x)='string' and length(trim(x#>>'{}'))=0)) or jsonb_typeof(a->'overlapsKeyMoment') not in ('null','boolean') or jsonb_typeof(a->'onKeyDimension') not in ('null','boolean') or (a->'intentImpact'<>'null'::jsonb and a->>'intentImpact' not in ('반전','약화','국소')) or (a->'severity'<>'null'::jsonb and a->>'severity' not in ('high','mid','low')) or (p_summary->>'subtextStatus'='not_provided' and exists(select 1 from (values(a->'whyOdd'),(a->'likelyCause'),(a->'impactOnIntent'),(a->'overlapsKeyMoment'),(a->'onKeyDimension'),(a->'intentImpact'),(a->'severity'),(a->'severityReason')) v(x) where x<>'null'::jsonb)) then raise exception 'invalid_summary_anomaly'; end if; expected_start:=((split_part(a->>'start',':',1)::integer*60)+split_part(a->>'start',':',2)::integer)*1000; expected_end:=((split_part(a->>'end',':',1)::integer*60)+split_part(a->>'end',':',2)::integer)*1000; if expected_start>expected_end then raise exception 'invalid_summary_anomaly_range'; end if; expected_start:=least(expected_start,duration); expected_end:=least(expected_end,duration); if (select array_agg(k order by k) from jsonb_object_keys(c) k)<>array['dimension','endMs','id','priority','severity','startMs','text'] or (c->>'priority')::integer<>idx or c->>'text'<>a->>'what' or c->>'dimension'<>a->>'dimension' or c->'severity' is distinct from a->'severity' or (c->>'startMs')::integer<>expected_start or (c->>'endMs')::integer<>expected_end then raise exception 'invalid_summary_candidate'; end if;
  insert into public.observations(id,session_id,take_id,user_id,timestamp_start_ms,timestamp_end_ms,observation_text,confidence,confirmation_state,blocked_for_questioning,candidate_id,priority,dimension,severity,source_run_id) values((c->>'id')::uuid,p_session_id,take,p_user_id,(c->>'startMs')::integer,(c->>'endMs')::integer,c->>'text',null,'unasked',false,(c->>'id')::uuid,idx,c->>'dimension',c->>'severity',p_run_id);
 end loop;
 update public.ai_runs set status='completed',response_schema_version='summary-response.v1',model=p_model,prompt_version=p_prompt_version,safe_error_code=null,completed_at=now(),updated_at=now() where id=p_run_id and session_id=p_session_id and user_id=p_user_id and status='running';
 return jsonb_build_object('session_id',p_session_id,'run_id',p_run_id);
end $$;

create or replace function public.acttub_append_pipeline_turn(p_session_id uuid,p_user_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare expected integer; actor jsonb; agent jsonb; conversation_count integer; begin
 select substantive_answer_count into expected from public.practice_sessions s where s.id=p_session_id and s.user_id=p_user_id and s.interview_status in ('active','paused') and s.deletion_status='active' and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found or expected<>(p_payload->>'expectedSubstantiveAnswerCount')::integer or expected>=10 then raise exception 'turn_conflict'; end if;
 select count(*) into conversation_count from public.interview_turns where session_id=p_session_id and user_id=p_user_id and role='actor' and kind in ('answer','unknown'); if conversation_count>=10 then raise exception 'turn_conflict'; end if;
 actor:=p_payload->'actorTurn'; agent:=p_payload->'agentTurn';
 if p_payload->'currentInput'->>'command' not in ('start','observation_update','answer','manual_stop','resume') or ((p_payload->'currentInput'->>'command') in ('start','observation_update','manual_stop','resume') and actor<>'null'::jsonb) or ((p_payload->'currentInput'->>'command')='resume' and not exists(select 1 from public.practice_sessions where id=p_session_id and interview_status='paused')) then raise exception 'invalid_current_input'; end if;
 if jsonb_array_length(p_payload->'reportEvidence'->'observationIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x) or jsonb_array_length(p_payload->'reportEvidence'->'answerTurnIds')<>(select count(distinct x) from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) or exists(select 1 from jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds') x where not exists(select 1 from public.interview_turns t where t.id=x::uuid and t.session_id=p_session_id and t.user_id=p_user_id and t.role='actor' and t.kind='answer' and t.report_evidence_selected) and not (actor is not null and actor<>'null'::jsonb and actor->>'id'=x and actor->>'kind'='answer' and coalesce((actor->>'reportEvidenceSelected')::boolean,false))) then raise exception 'invalid_report_evidence'; end if;
 if (p_payload->'currentInput'->>'command')='answer' and (actor is null or actor='null'::jsonb or actor->>'kind' not in ('answer','unknown') or p_payload->'currentInput'->>'answerTurnId'<>actor->>'id' or p_payload->'currentInput'->>'answer'<>actor->>'content') then raise exception 'current_input_mismatch'; end if;
 if actor is not null and actor<>'null'::jsonb then if actor->>'kind' not in ('answer','unknown') or (actor->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) then raise exception 'invalid_actor_turn'; end if; insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,source_observation_ids,report_evidence_selected) values((actor->>'id')::uuid,p_session_id,p_user_id,(actor->>'sequence')::integer,'actor',actor->>'kind',actor->>'content',array(select jsonb_array_elements_text(actor->'sourceObservationIds'))::uuid[],coalesce((actor->>'reportEvidenceSelected')::boolean,false)); if actor->>'kind'='answer' then expected:=expected+1; end if; end if;
 if (agent->>'sequence')::integer<>(select coalesce(max(sequence)+1,0) from public.interview_turns where session_id=p_session_id) or agent->>'kind' not in ('question','closing') then raise exception 'invalid_agent_turn'; end if;
 if exists(select 1 from jsonb_array_elements_text(agent->'sourceObservationIds') x where not exists(select 1 from public.observations o where o.id=x::uuid and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) then raise exception 'invalid_source_observation'; end if;
 insert into public.interview_turns(id,session_id,user_id,sequence,role,kind,content,question_focus,source_observation_ids) values((agent->>'id')::uuid,p_session_id,p_user_id,(agent->>'sequence')::integer,'agent',agent->>'kind',agent->>'content',agent->>'questionFocus',array(select jsonb_array_elements_text(agent->'sourceObservationIds'))::uuid[]);
 update public.practice_sessions set substantive_answer_count=expected,interview_status='active',report_evidence_observation_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'observationIds'))::uuid[],report_evidence_answer_turn_ids=array(select jsonb_array_elements_text(p_payload->'reportEvidence'->'answerTurnIds'))::uuid[],updated_at=now() where id=p_session_id;
 return jsonb_build_object('substantive_answer_count',expected);
end $$;

create or replace function public.acttub_complete_interview(p_session_id uuid,p_user_id uuid,p_payload jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$ declare reason text:=p_payload->>'completionReason'; stat text:=p_payload->>'status'; obs uuid[]:=array(select jsonb_array_elements_text(p_payload->'observationIds'))::uuid[]; turns uuid[]:=array(select jsonb_array_elements_text(p_payload->'answerTurnIds'))::uuid[]; n integer; conversation_count integer; agent_run_id text:=p_payload->>'agentRunId'; begin
 select substantive_answer_count into n from public.practice_sessions where id=p_session_id and user_id=p_user_id and deletion_status='active' and interview_status in ('active','paused') for update; if not found then raise exception 'session_not_mutable'; end if;
 select count(*) into conversation_count from public.interview_turns where session_id=p_session_id and user_id=p_user_id and role='actor' and kind in ('answer','unknown');
 if (stat='completed' and reason not in ('interview_complete_report_ready','manual_stop_report_ready','hard_limit_report_ready')) or (stat='paused' and reason<>'manual_stop_paused') or (stat='completed_without_report' and reason not in ('insufficient_confirmed_evidence','insufficient_interview_evidence')) then raise exception 'invalid_completion'; end if;
 if reason='interview_complete_report_ready' and n<5 or reason in ('hard_limit_report_ready','insufficient_interview_evidence') and conversation_count<>10 then raise exception 'invalid_completion_count'; end if;
 if cardinality(obs)<>cardinality(array(select distinct x from unnest(obs) x)) or cardinality(turns)<>cardinality(array(select distinct x from unnest(turns) x)) then raise exception 'duplicate_report_evidence'; end if;
 if stat='completed' then if cardinality(obs)=0 or cardinality(turns)=0 or exists(select 1 from unnest(obs) x where not exists(select 1 from public.observations o where o.id=x and o.session_id=p_session_id and o.user_id=p_user_id and o.confirmation_state='accepted' and not o.blocked_for_questioning)) or exists(select 1 from unnest(turns) x where not exists(select 1 from public.interview_turns t where t.id=x and t.session_id=p_session_id and t.user_id=p_user_id and t.role='actor' and t.kind='answer' and length(trim(t.content))>0 and t.report_evidence_selected)) then raise exception 'invalid_report_evidence'; end if; else if cardinality(obs)<>0 or cardinality(turns)<>0 then raise exception 'evidence_not_allowed'; end if; end if;
 update public.practice_sessions set interview_status=stat,completion_reason=reason,report_evidence_observation_ids=obs,report_evidence_answer_turn_ids=turns,updated_at=now() where id=p_session_id;
 if agent_run_id is not null and length(trim(agent_run_id))>0 then
  update public.ai_runs set status='completed',response_schema_version='agent-turn.v1',model=coalesce(nullif(trim(p_payload->>'model'),''),model),prompt_version=coalesce(nullif(trim(p_payload->>'promptVersion'),''),prompt_version),completed_at=coalesce(completed_at,now()),updated_at=now() where id=agent_run_id::uuid and session_id=p_session_id and user_id=p_user_id and stage='agent' and status in ('running','completed');
  if not found then raise exception 'agent_run_not_running'; end if;
 end if;
 return jsonb_build_object('status',stat,'completion_reason',reason);
end $$;

create or replace function public.acttub_complete_report_run(p_session_id uuid,p_user_id uuid,p_run_id uuid,p_report jsonb,p_model text,p_prompt_version text)
returns jsonb language plpgsql security definer set search_path=public as $$ declare sec jsonb:=p_report->'sections'; existing public.ai_reports; e record; range jsonb; begin
 select * into existing from public.ai_reports where session_id=p_session_id and user_id=p_user_id for update; if found then return jsonb_build_object('schemaVersion',existing.schema_version,'sections',jsonb_build_object('oneLineSummary',existing.one_line_summary,'primaryReviewPoint',existing.primary_review_point,'confirmedEvidence',existing.confirmed_evidence,'actorDiscovery',existing.actor_discovery,'groundedEncouragement',existing.grounded_encouragement,'nextPracticeStep',existing.next_practice_step)); end if;
 perform 1 from public.ai_runs r join public.practice_sessions s on s.id=r.session_id and s.user_id=r.user_id where r.id=p_run_id and r.session_id=p_session_id and r.user_id=p_user_id and r.stage='report' and r.status='running' and s.interview_status='completed' and s.completion_reason in ('interview_complete_report_ready','manual_stop_report_ready','hard_limit_report_ready') and s.required_consent_version_snapshot=public.current_acttub_terms_version() and s.ai_processing_consent_version_snapshot=public.current_acttub_ai_processing_consent_version() and exists(select 1 from public.profiles p where p.id=p_user_id and p.status='active' and p.required_consent_version=public.current_acttub_terms_version() and p.required_consent_at is not null and p.ai_processing_consent_version=public.current_acttub_ai_processing_consent_version() and p.ai_processing_consent_at is not null) for update; if not found then raise exception 'report_not_ready'; end if;
 if (select array_agg(k order by k) from jsonb_object_keys(p_report) k)<>array['schemaVersion','sections'] or p_report->>'schemaVersion'<>'report.v1' or (select array_agg(k order by k) from jsonb_object_keys(sec) k)<>array['actorDiscovery','confirmedEvidence','groundedEncouragement','nextPracticeStep','oneLineSummary','primaryReviewPoint'] then raise exception 'invalid_report'; end if;
 for e in select key,value from jsonb_each(sec) loop
  if (select array_agg(k order by k) from jsonb_object_keys(e.value) k)<>array['content','observationEvidenceIds','status','timestampRange','turnEvidenceIds'] or e.value->>'status' not in ('confirmed','not_confirmed') then raise exception 'invalid_report_section'; end if;
  if e.value->>'status'='not_confirmed' then
   if e.key in ('oneLineSummary','primaryReviewPoint','confirmedEvidence') or e.value->'content'<>'null'::jsonb or e.value->'timestampRange'<>'null'::jsonb or jsonb_array_length(e.value->'observationEvidenceIds')<>0 or jsonb_array_length(e.value->'turnEvidenceIds')<>0 then raise exception 'invalid_unconfirmed_section'; end if;
  else
   if length(trim(e.value->>'content'))=0 then raise exception 'invalid_confirmed_section'; end if;
   if e.key in ('oneLineSummary','confirmedEvidence') then
    if jsonb_array_length(e.value->'observationEvidenceIds')=0 or jsonb_array_length(e.value->'turnEvidenceIds')=0 then raise exception 'invalid_report_evidence'; end if;
   elsif e.key='primaryReviewPoint' then
    if jsonb_array_length(e.value->'observationEvidenceIds')=0 or jsonb_array_length(e.value->'turnEvidenceIds')<>0 or e.value->'timestampRange'='null'::jsonb then raise exception 'invalid_report_evidence'; end if;
   elsif e.key='actorDiscovery' then
    if jsonb_array_length(e.value->'turnEvidenceIds')=0 then raise exception 'invalid_report_evidence'; end if;
   elsif e.key='groundedEncouragement' then
    if jsonb_array_length(e.value->'observationEvidenceIds')=0 then raise exception 'invalid_report_evidence'; end if;
   end if;
   if exists(select 1 from jsonb_array_elements_text(e.value->'observationEvidenceIds') x where not exists(select 1 from public.practice_sessions s join public.observations o on o.session_id=s.id and o.user_id=s.user_id where s.id=p_session_id and o.id=x::uuid and o.confirmation_state='accepted' and not o.blocked_for_questioning and o.id=any(s.report_evidence_observation_ids)))) then raise exception 'invalid_report_evidence'; end if;
   if exists(select 1 from jsonb_array_elements_text(e.value->'turnEvidenceIds') x where not exists(select 1 from public.practice_sessions s join public.interview_turns t on t.session_id=s.id and t.user_id=s.user_id where s.id=p_session_id and (t.id=x::uuid and ((e.key in ('oneLineSummary','confirmedEvidence') and t.role='actor' and t.kind='answer' and t.report_evidence_selected and t.id=any(s.report_evidence_answer_turn_ids)) or (e.key in ('actorDiscovery','groundedEncouragement','nextPracticeStep') and ((t.role='actor' and t.kind='answer' and t.report_evidence_selected and t.id=any(s.report_evidence_answer_turn_ids)) or (t.role='actor' and t.kind='actor_correction' and exists(select 1 from public.actor_corrections c where c.session_id=p_session_id and c.user_id=p_user_id and c.correction_by_turn_id=t.id))))))))) then raise exception 'invalid_report_evidence'; end if;
   range:=e.value->'timestampRange'; if range<>'null'::jsonb then if (select array_agg(k order by k) from jsonb_object_keys(range) k)<>array['endMs','startMs'] or (range->>'endMs')::integer<(range->>'startMs')::integer then raise exception 'invalid_report_timestamp'; end if; if not exists(select 1 from jsonb_array_elements_text(e.value->'observationEvidenceIds') x join public.observations o on o.id=x::uuid and o.session_id=p_session_id where o.timestamp_start_ms=(range->>'startMs')::integer and o.timestamp_end_ms=(range->>'endMs')::integer) and not exists(select 1 from jsonb_array_elements_text(e.value->'turnEvidenceIds') x join public.actor_corrections c on c.correction_by_turn_id=x::uuid and c.session_id=p_session_id join public.observations o on o.id=c.observation_id where o.timestamp_start_ms=(range->>'startMs')::integer and o.timestamp_end_ms=(range->>'endMs')::integer) then raise exception 'invalid_report_timestamp'; end if; elsif e.key='primaryReviewPoint' then raise exception 'invalid_report_timestamp'; end if;
  end if;
 end loop;
 insert into public.ai_reports(session_id,user_id,source_run_id,schema_version,completion_reason,one_line_summary,primary_review_point,confirmed_evidence,actor_discovery,grounded_encouragement,next_practice_step) select p_session_id,p_user_id,p_run_id,'report.v1',completion_reason,sec->'oneLineSummary',sec->'primaryReviewPoint',sec->'confirmedEvidence',sec->'actorDiscovery',sec->'groundedEncouragement',sec->'nextPracticeStep' from public.practice_sessions where id=p_session_id;
 update public.ai_runs set status='completed',response_schema_version='report.v1',model=p_model,prompt_version=p_prompt_version,completed_at=now(),updated_at=now() where id=p_run_id and session_id=p_session_id and user_id=p_user_id and status='running'; if not found then raise exception 'report_run_conflict'; end if;
 return p_report;
end $$;

revoke execute on function public.acttub_complete_summary_run(uuid,uuid,uuid,jsonb,jsonb,text,text) from public,anon,authenticated;
grant execute on function public.acttub_complete_summary_run(uuid,uuid,uuid,jsonb,jsonb,text,text) to service_role;
revoke execute on function public.acttub_complete_report_run(uuid,uuid,uuid,jsonb,text,text) from public,anon,authenticated;
grant execute on function public.acttub_complete_report_run(uuid,uuid,uuid,jsonb,text,text) to service_role;
